const green = (v) => `<span class="green">${v}</span>`
const purple = (v) => `<span class="purple">${v}</span>`
const red = (v) => `<span class="red">${v}</span>`
const stat = (v) => `<span class="stat ${v}"></span>`

// prettier-ignore
const characters = {
  wellRounded: {
    name: 'wellRounded',
    nameText: 'Well Rounded',
    texts: [
      `${green('+5')} Max HP`,
      `${green('+5%')} Speed`,
      `${green('+8')} Harvesting`,
    ],
    weapons: ['knife', 'stick', 'fist', 'cactiClub', 'ghostFlint', 'wrench', 'lute', 'pistol', 'smg', 'doubleBarrelShotgun', 'slingshot', 'taser', 'wand', 'icicle'],
    position: [384, 672],
  },
  brawler: {
    name: 'brawler',
    nameText: 'Brawler',
    texts: [
      `${green('+50% Attack Speed')} with ${green('Unarmed')} weapons`,
      `You start with ${green('1 Fist')}`,
      `${green('+15%')} Dodge`,
      `${red('-50')} Range`,
      `${red('-50')} Ranged Damage`,
    ],
    weapons: ['fist', 'hand', 'claw'],
    startWeapon: 'fist',
    position: [384, 0],
  },
  crazy: {
    name: 'crazy',
    nameText: 'Crazy',
    texts: [
      `${green('+100 Range')} with ${green('Precise')} weapons`,
      `${green('+25%')} Attack Speed`,
      `You start with ${green('1 Knife')}`,
      `${red('-30%')} Dodge`,
      `${red('-10')} Engineering`,
      `${red('-10')} Ranged Damage`,
    ],
    weapons: ['knife', 'thiefDagger', 'scissors', 'lightningShiv', 'claw', 'sharpTooth', 'shuriken', 'icicle'],
    startWeapon: 'knife',
    position: [384, 96],
  },
  ranger: {
    name: 'ranger',
    nameText: 'Ranger',
    texts: [
      `${green('+50')} Range`,
      `You start with ${green('1 Pistol')}`,
      `${green('Ranged Damage')} modifications are increased by ${green('50%')}`,
      `You can't equip melee weapons`,
      `${red('Max HP')} modifications are reduced by ${red('25%')}`,
    ],
    weapons: ['pistol', 'smg', 'revolver', 'doubleBarrelShotgun', 'laserGun', 'shredder', 'crossbow', 'slingshot'],
    startWeapon: 'pistol',
    position: [576, 576],
  },
  mage: {
    name: 'mage',
    nameText: 'Mage',
    texts: [
      `${green('Elemental Damage')} modifications are increased by ${green('25%')}`,
      `You start with ${green('1 Snake')}`,
      `You start with ${green('1 Scared Sausage')}`,
      `${red('Melee Damage')} modifications are reduced by ${red('100%')}`,
      `${red('Ranged Damage')} modifications are reduced by ${red('100%')}`,
      `${red('Engineering')} modifications are reduced by ${red('50%')}`,
    ],
    weapons: ['torch', 'plank', 'lightningShiv', 'wand', 'taser', 'icicle', 'smg', 'doubleBarrelShotgun'],
    position: [480, 480],
  },
  chunky: {
    name: 'chunky',
    nameText: 'Chunky',
    texts: [
      `${green('Max HP')} modifications are increased by ${green('25%')}`,
      `${green('+1% Damage')} for every permanent ${green('3 Max HP')} you have`,
      `${green('+3')} HP recovered from consumables`,
      `${red('-100%')} Life Steal`,
      `${red('HP Regeneration')} modifications are reduced by ${red('50%')}`,
      `${red('% Dodge')} modifications are reduced by ${red('50%')}`,
      `${red('% Speed')} modifications are reduced by ${red('100%')}`,
    ],
    weapons: ['fist', 'cactiClub', 'rock', 'stick', 'torch', 'plank', 'chopper', 'pruner', 'spikyShield', 'spoon', 'doubleBarrelShotgun', 'taser', 'ghostScepter', 'shredder', 'revolver'],
    position: [288, 96],
  },
  old: {
    name: 'old',
    nameText: 'Old',
    texts: [
      `${green('-25%')} Enemy Speed`,
      `${green('+10')} Harvesting`,
      '-33% Map Size',
      '-10% Enemies',
      `${red('-10%')} Speed`,
    ],
    weapons: ['scissors', 'screwdriver', 'wrench', 'rock', 'plank', 'chopper', 'pruner', 'lute', 'sickle', 'doubleBarrelShotgun', 'revolver', 'taser', 'wand', 'icicle'],
    position: [288, 576],
  },
  lucky: {
    name: 'lucky',
    nameText: 'Lucky',
    texts: [
      `${green('+100')} Luck`,
      `${green('Luck')} modifications are increased by ${green('25%')}`,
      `${green('75%')} chance to deal ${green('1')} (15%${stat('Luck')}) damage to a random enemy when you pick up a material`,
      `${red('-60%')} Attack Speed`,
      `${red('-50%')} XP Gain`,
    ],
    weapons: ['stick', 'rock', 'fist', 'chopper', 'plank', 'screwdriver', 'joustingLance', 'torch', 'pruner', 'lute', 'slingshot', 'wand', 'icicle', 'flute'],
    position: [384, 480],
  },
  mutant: {
    name: 'mutant',
    nameText: 'Mutant',
    texts: [
      `${green('-66%')} XP required to level up`,
      `${red('+50%')} Items Price`,
    ],
    weapons: ['cactiClub', 'ghostAxe', 'stick', 'quarterstaff', 'rock', 'plank', 'lightningShiv', 'brick', 'doubleBarrelShotgun', 'smg', 'revolver', 'shredder', 'crossbow', 'taser', 'wand', 'icicle'],
    position: [96, 576],
  },
  generalist: {
    name: 'generalist',
    nameText: 'Generalist',
    texts: [
      `${green('+2 Melee Damage')} for every ${green('1 Ranged Damage')} you have`,
      `${green('+1 Ranged Damage')} for every ${green('2 Melee Damage')} you have`,
      `You can only equip ${green('3')} melee weapons and ${green('3')} ranged weapons at a time`,
    ],
    weapons: ['fist', 'cactiClub', 'ghostAxe', 'ghostFlint', 'lightningShiv', 'knife', 'scissors', 'spear', 'shuriken', 'doubleBarrelShotgun', 'smg', 'shredder', 'revolver', 'laserGun', 'slingshot', 'ghostScepter', 'javelin'],
    position: [576, 288],
  },
  loud: {
    name: 'loud',
    nameText: 'Loud',
    texts: [
      `${green('+30%')} Damage`,
      `+50% Enemies`,
      `${red('-3 Harvesting')} at the end of a wave`,
    ],
    weapons: ['cactiClub', 'ghostAxe', 'ghostFlint', 'lightningShiv', 'thiefDagger', 'claw', 'spear', 'torch', 'rock', 'hatchet', 'plank', 'wrench', 'joustingLance', 'quarterstaff', 'pruner', 'screwdriver', 'doubleBarrelShotgun', 'pistol', 'smg', 'shredder', 'icicle', 'shuriken', 'slingshot', 'crossbow', 'javelin'],
    position: [288, 480],
  },
  multitasker: {
    name: 'multitasker',
    nameText: 'Multitasker',
    texts: [
      `${green('+20%')} Damage`,
      `You can equip up to ${green('12')} weapons at a time`,
      `${red('-5% Damage')} for every weapon you have`,
    ],
    weapons: ['cactiClub', 'fist', 'claw', 'knife', 'spear', 'stick', 'quarterstaff', 'lightningShiv', 'screwdriver', 'wrench', 'ghostFlint', 'ghostAxe', 'plank', 'chopper', 'hatchet', 'joustingLance', 'pruner', 'rock', 'spikyShield', 'sharpTooth', 'hikingPole', 'lute', 'doubleBarrelShotgun', 'smg', 'revolver', 'laserGun', 'wand', 'icicle', 'slingshot', 'taser', 'shuriken', 'crossbow'],
    position: [0, 576],
  },
  wildling: {
    name: 'wildling',
    nameText: 'Wildling',
    texts: [
      `${red('+30% Life Steal')} with ${green('Primitive')} weapons`,
      `You start with ${green('1 Stick')}`,
      `You can't equip weapons above tier ${red('II')}`,
    ],
    weapons: ['stick', 'spear', 'torch', 'rock', 'cactiClub', 'hatchet', 'quarterstaff', 'sharpTooth', 'slingshot', 'javelin'],
    startWeapon: 'stick',
    position: [480, 672],
  },
  pacifist: {
    name: 'pacifist',
    nameText: 'Pacifist',
    texts: [
      `Gain ${green('0.65')} material and XP for every living enemy at the end of a wave`,
      `You start with ${green('1 Lumberjack Shirt')}`,
      `${red('-100%')} Damage`,
      `${red('-100')} Engineering`,
    ],
    weapons: ['hand', 'pruner', 'taser'],
    position: [480, 576],
  },
  gladiator: {
    name: 'gladiator',
    nameText: 'Gladiator',
    texts: [
      `${green('+20% Attack Speed')} for every weapon you have`,
      `${green('+5')} Melee Damage`,
      `You can't equip ranged weapons`,
      `${red('-40%')} Attack Speed`,
      `${red('-30')} Luck`,
    ],
    weapons: ['spear', 'joustingLance', 'cactiClub', 'torch', 'thiefDagger', 'knife', 'plank', 'ghostAxe', 'ghostFlint', 'sharpTooth', 'fist', 'claw', 'quarterstaff', 'hatchet', 'lightningShiv'],
    position:  [96, 384],
  },
  saver: {
    name: 'saver',
    nameText: 'Saver',
    texts: [
      `${green('+15')} Harvesting`,
      `${green('+1% Damage')} for every ${green('25 Materials')} you have`,
      `You start with ${green('1 Piggy Bank')}`,
      `${red('+50%')} Items Price`,
    ],
    weapons: ['fist', 'chopper', 'thiefDagger', 'ghostFlint', 'pruner', 'lightningShiv', 'cactiClub', 'spear', 'lute', 'sickle', 'pistol', 'revolver', 'laserGun', 'taser', 'wand', 'icicle'],
    position: [672, 288],
  },
  sick: {
    name: 'sick',
    nameText: 'Sick',
    texts: [
      `${green('+12')} Max HP`,
      `${green('+25%')} Life Steal`,
      `You take ${red('1')} damage per second (does not fiv invulnerability time)`,
      `${red('-100')} HP Regeneration`,
    ],
    weapons: ['fist', 'scissors', 'hatchet', 'ghostFlint', 'cactiClub', 'lightningShiv', 'sharpTooth', 'pruner', 'sickle', 'ghostScepter', 'slingshot', 'smg', 'medicalGun'],
    position: [672, 384],
  },
  farmer: {
    name: 'farmer',
    nameText: 'Farmer',
    texts: [
      `${green('+20')} Harvesting`,
      `Harvesting increases by an additional ${green('3%')} at the end of a wave`,
      `${green('+1 Harvesting')} when picking up a consumable while at maximum health`,
      `${red('-50%')} materials dropped`,
    ],
    weapons: ['hand', 'spear', 'stick', 'torch', 'quarterstaff', 'screwdriver', 'pruner', 'thiefDagger', 'wrench', 'lute', 'sickle', 'laserGun', 'wand', 'doubleBarrelShotgun', 'slingshot', 'potatoThrower'],
    position: [288, 288],
  },
  ghost: {
    name: 'ghost',
    nameText: 'Ghost',
    texts: [
      `${green('+10 Damage')} with ${green('Ethereal')} weapons`,
      `${green('+30%')} Dodge`,
      `Dodge is capped at ${green('90%')}`,
      `${red('-100')} Armor`,
    ],
    weapons: ['ghostFlint', 'ghostAxe', 'ghostScepter'],
    position: [0, 384],
  },
  speedy: {
    name: 'speedy',
    nameText: 'Speedy',
    texts: [
      `${green('+30%')} Speed`,
      `${green('+1 Melee Damage')} for every ${green('2% Speed')} you have`,
      `${red('-100 Armor')} while standing still`,
      `${red('-3')} Armor`,
    ],
    weapons: ['fist', 'claw', 'knife', 'thiefDagger', 'stick', 'spear', 'quarterstaff', 'joustingLance', 'screwdriver', 'ghostFlint', 'pruner', 'hikingPole', 'shuriken', 'javelin'],
    position: [672, 576],
  },
  entrepreneur: {
    name: 'entrepreneur',
    nameText: 'Entrepreneur',
    texts: [
      `${green('-25%')} Items Price`,
      `${green('Harvesting')} modifications are increased by ${green('50%')}`,
      `Gain ${green('25%')} more materials from recycling items`,
      `${red('-100%')} of your materials at the start of waves`,
      `${red('Damage')} modifications are reduced by ${red('50%')}`,
    ],
    weapons: ['fist', 'claw', 'hand', 'knife', 'thiefDagger', 'pruner', 'quarterstaff', 'hatchet', 'ghostFlint', 'wrench', 'plank', 'hikingPole', 'lute', 'sickle', 'pistol', 'doubleBarrelShotgun', 'taser', 'shuriken', 'crossbow', 'icicle'],
    position: [96, 288],
  },
  engineer: {
    name: 'engineer',
    nameText: 'Engineer',
    texts: [
      `${green('+10')} Engineering`,
      `${green('Engineering')} modifications are increased by ${green('25%')}`,
      `You start with ${green('1 Wrench')}`,
      'Structures spawn close from each other',
      `${red('Damage')} modifications are reduced by ${red('50%')}`,
    ],
    weapons: ['wrench', 'screwdriver', 'plank', 'hammer'],
    startWeapon: 'wrench',
    position: [0, 288],
  },
  explorer: {
    name: 'explorer',
    nameText: 'Explorer',
    texts: [
      'More trees spawn',
      `You start with ${green('1 Lumberjack Shirt')}`,
      `${green('+10%')} Speed`,
      `${green('+50%')} pickup range`,
      '+33% Map Size',
      '+25% Enemies',
      `${red('-50%')} materials dropped from enemies`,
      `${red('+10%')} Enemy Speed`,
      `${red('-40%')} Damage`,
    ],
    weapons: ['hand', 'cactiClub', 'screwdriver', 'thiefDagger', 'wrench', 'stick', 'torch', 'chopper', 'plank', 'hatchet', 'joustingLance', 'ghostAxe', 'hikingPole', 'spoon', 'crossbow', 'shredder', 'taser', 'wand'],
    position:  [192, 288],
  },
  doctor: {
    name: 'doctor',
    nameText: 'Doctor',
    texts: [
      `${green('+200% Attack Speed')} with ${green('Medical')} weapons`,
      `${green('+5')} HP Regeneration`,
      `${green('+5')} Harvesting`,
      `${green('HP Regeneration')} modifications are increased by ${green('100%')}`,
      `${red('-100%')} Attack Speed`,
      `${red('Armor')} modifications are reduced by ${red('50%')}`,
    ],
    weapons: ['scissors', 'medicalGun'],
    position: [384, 192],
  },
  hunter: {
    name: 'hunter',
    nameText: 'Hunter',
    texts: [
      `${green('+100')} Range`,
      `${green('+1% Damage')} for every ${green('10 Range')} you have`,
      `${green('% Crit Chance')} modifications are increased by ${green('25%')}`,
      `${red('Harvesting')} modifications are reduced by ${red('100%')}`,
      `${red('Max HP')} modifications are reduced by ${red('33%')}`,
    ],
    weapons: ['cactiClub', 'thiefDagger', 'spear', 'claw', 'scissors', 'hikingPole', 'shuriken', 'doubleBarrelShotgun', 'crossbow', 'icicle', 'javelin'],
    position: [480, 384],
  },
  artificer: {
    name: 'artificer',
    nameText: 'Artificer',
    texts: [
      `${green('+175%')} Explosion Damage`,
      `${green('+4% Explosion Size')} for every ${green('1 Elemental Damage')} you have`,
      `${green('+100% Damage')} with ${green('Tool')} weapons`,
      `${red('-100%')} Damage`,
      `${red('Armor')} modifications are reduced by ${red('50%')}`,
    ],
    weapons: ['plank', 'screwdriver', 'wrench', 'shredder'],
    position: [192, 0],
  },
  armsDealer: {
    name: 'armsDealer',
    nameText: 'Arms Dealer',
    texts: [
      `${green('-95%')} Weapons Price`,
      `${green('+30')} Harvesting`,
      `${green('Damage')} modifications are increased by ${green('33%')}`,
      `You start with ${green('1 Dangerous Bunny')}`,
      'Shops always sell at least one weapon',
      'All of your weapons are destroyed when entering a shop',
    ],
    weapons: ['pistol'],
    position: [96, 0],
  },
  streamer: {
    name: 'streamer',
    nameText: 'Streamer',
    texts: [
      `${green('+3%')} of your materials (${green('+25')} max) per second while standing still`,
      `${green('+40% Damage')} while moving`,
      `${green('+40% Attack Speed')} while moving`,
      `${green('+2 Armor')} for every ${green('1 Structure')} you have`,
      `${red('-50%')} materials dropped`,
      `${red('-1% Damage')} for every ${green('15 Materials')} you have`,
      `${red('-1% Speed')} for every ${green('30 Materials')} you have`,
    ],
    weapons: ['hand', 'stick', 'cactiClub', 'ghostFlint', 'ghostAxe', 'scissors', 'screwdriver', 'wrench', 'spear', 'plank', 'pruner', 'spikyShield', 'crossbow', 'doubleBarrelShotgun', 'laserGun', 'medicalGun', 'pistol', 'shredder', 'smg', 'revolver', 'slingshot', 'ghostScepter', 'taser', 'wand', 'icicle', 'javelin'],
    position: [0, 672],
  },
  cyborg: {
    name: 'cyborg',
    nameText: 'Cyborg',
    texts: [
      `You start with ${green('1 Minigun')}`,
      `${green('Ranged Damage')} modifications are increased by ${green('200%')}`,
      `${green('+100%')} of your ${green('Ranged Damage')} are temporarily converted into ${green('Engineering')} halfway through a wave (${green('1 Ranged Damage')} = ${green('2 Engineering')})`,
      `${red('Engineering')} modifications are reduced by ${red('75%')}`,
      `${red('Melee Damage')} modifications are reduced by ${red('100%')}`,
      `${red('Elemental Damage')} modifications are reduced by ${red('100%')}`,
    ],
    weapons: ['wrench', 'screwdriver', 'plank', 'brick', 'pistol', 'smg', 'revolver', 'doubleBarrelShotgun', 'crossbow'],
    startWeapon: 'minigun',
    position: [96, 192],
  },
  glutton: {
    name: 'glutton',
    nameText: 'Glutton',
    texts: [
      `${green('+50')} Luck`,
      `${green('+1 Explosion Damage')} when picking up a consumable while at maximum health`,
      `Consumable have a ${green('100%')} chance to explode for ${green('10')} (+500% ${stat('MeleeDamage')}) damage when picked up`,
      `${red('+25%')} Items Price`,
      `${red('-25%')} XP Gain`,
    ],
    weapons: ['pruner', 'chopper', 'thiefDagger', 'fist', 'joustingLance', 'screwdriver', 'plank', 'lute', 'spoon', 'shredder', 'flute'],
    position: [192, 384],
  },
  jack: {
    name: 'jack',
    nameText: 'Jack',
    texts: [
      `${green('+125%')} damage against bosses and elites`,
      `${green('+200%')} materials dropped`,
      '-70% Enemies',
      `${red('+175%')} Enemy health`,
      `${red('+35%')} Enemy damage`,
    ],
    weapons: ['knife', 'joustingLance', 'wrench', 'torch', 'hatchet', 'stick', 'spear', 'spikyShield', 'brick', 'lute', 'spoon', 'shuriken', 'laserGun', 'revolver', 'crossbow', 'taser', 'wand', 'icicle', 'flute'],
    position: [576, 384],
  },
  lich: {
    name: 'lich',
    nameText: 'Lich',
    texts: [
      `${green('+10')} HP Regeneration`,
      `${green('+10%')} Life Steal`,
      `${green('100%')} chance to deal ${green('10')} (100% ${stat('MaxHP')}) damage to a random enemy when you heal`,
      `${red('Damage')} modifications are reduced by ${red('50%')}`,
    ],
    weapons: ['scissors', 'chopper', 'thiefDagger', 'stick', 'knife', 'ghostFlint', 'sharpTooth', 'pruner', 'hatchet', 'rock', 'spikyShield', 'lightningShiv', 'spoon', 'ghostScepter', 'medicalGun', 'smg', 'wand', 'icicle', 'slingshot', 'crossbow'],
    position: [192, 480],
  },
  apprentice: {
    name: 'apprentice',
    nameText: 'Apprentice',
    texts: [
      `${green('+2 Melee Damage')} when you level up`,
      `${green('+1 Ranged Damage')} when you level up`,
      `${green('+1 Elemental Damage')} when you level up`,
      `${green('+1 Engineering')} when you level up`,
      `${red('-2 Max HP')} when you level up`,
    ],
    weapons: ['fist', 'knife', 'lightningShiv', 'cactiClub', 'quarterstaff', 'ghostFlint', 'ghostAxe', 'hatchet', 'torch', 'plank', 'pruner', 'screwdriver', 'wrench', 'brick', 'medicalGun', 'smg', 'doubleBarrelShotgun', 'shredder', 'slingshot', 'taser', 'icicle', 'shuriken', 'ghostScepter'],
    position: [0, 0],
  },
  cryptid: {
    name: 'cryptid',
    nameText: 'Cryptid',
    texts: [
      'More trees spawn',
      `Gain ${green('12')} materials and XP for every living tree at the end of a wave`,
      `${green('+3 HP Regeneration')} for every current living tree`,
      `Dodge is capped at ${green('70%')}`,
      `${green('+3% Attack Speed')} until the end of the wave when you dodge an attack`,
      `${red('-100%')} Life Steal`,
      `${red('-100')} Range`,
      `${red('-50%')} materials dropped from enemies`,
    ],
    weapons: ['fist', 'hand', 'claw', 'knife', 'cactiClub', 'pruner', 'chopper', 'ghostAxe', 'thiefDagger', 'lightningShiv', 'ghostFlint', 'rock', 'stick', 'hatchet', 'joustingLance', 'screwdriver', 'plank', 'lute', 'sickle', 'ghostScepter', 'shredder', 'pistol', 'smg'],
    position: [576, 96],
  },
  fisherman: {
    name: 'fisherman',
    nameText: 'Fisherman',
    texts: [
      `${green('+5')} Max HP`,
      `${green('+20')} Harvesting`,
      `Shops always sell a ${green('Bait')}`,
      `${green('-100%')} Bait price`,
      `${green('+2 Harvesting')} for every ${green('1 Bait')} you have`,
      'Baits make some special enemies spawn throughout all future waves',
      `${red('-50%')} materials dropped from enemies`,
    ],
    weapons: ['knife', 'rock', 'spear', 'quarterstaff', 'spikyShield', 'torch', 'stick', 'sharpTooth', 'plank', 'pruner', 'scissors', 'pistol', 'smg', 'crossbow', 'doubleBarrelShotgun', 'laserGun', 'revolver', 'shredder', 'slingshot', 'icicle', 'javelin'],
    position: [384, 288],
  },
  golem: {
    name: 'golem',
    nameText: 'Golem',
    texts: [
      `${green('+20')} Max HP`,
      `${green('Max HP')} modifications are increased by ${green('33%')}`,
      `${green('Armor')} modifications are increased by ${green('33%')}`,
      `${green('+40% Attack Speed')} when you have less than 50% health`,
      `${green('+40% Speed')} when you have less than 50% health`,
      `You can't heal in any way`,
    ],
    weapons: ['cactiClub', 'chopper', 'fist', 'ghostAxe', 'hatchet', 'knife', 'plank', 'rock', 'spikyShield', 'stick', 'torch', 'brick', 'spoon', 'pistol', 'revolver', 'slingshot', 'crossbow', 'ghostScepter', 'flute'],
    position: [288, 384],
  },
  king: {
    name: 'king',
    nameText: 'King',
    texts: [
      `${green('+50')} Luck`,
      `${green('+25% Damage')} for every Tier IV weapon you have`,
      `${green('+25% Attack Speed')} for every Tier IV weapon you have`,
      `${green('+5 Max HP')} for every different Tier IV item you have`,
      `${red('-15% Damage')} for every Tier I weapon you have`,
      `${red('-15% Attack Speed')} for every Tier I weapon you have`,
      `${red('-2 Max HP')} for every different Tier I item you have`,
    ],
    weapons: ['fist', 'circularSaw', 'knife', 'hatchet', 'ghostAxe', 'lightningShiv', 'torch', 'plank', 'spear', 'joustingLance', 'sword', 'hammer', 'spikyShield', 'lute', 'trident', 'pistol', 'smg', 'crossbow', 'doubleBarrelShotgun', 'rocketLauncher', 'taser', 'fireball', 'flute', 'grenadeLauncher', 'javelin'],
    position: [0, 480],
  },
  renegade: {
    name: 'renegade',
    nameText: 'Renegade',
    texts: [
      `${green('+2')} projectiles`,
      `Projectiles pierce through ${green('1')} additional target`,
      `${green('+10% Damage')} for every different Tier I item you have`,
      `You can't equip melee weapons`,
      `${red('-400%')} Damage`,
      `${red('-50%')} Accuracy`,
      `${red('% Damage')} modifications are reduced by ${red('80%')}`,
    ],
    weapons: ['pistol', 'revolver', 'shredder', 'smg', 'laserGun', 'medicalGun', 'doubleBarrelShotgun', 'taser', 'wand', 'icicle', 'ghostScepter', 'crossbow', 'shuriken', 'slingshot', 'flute', 'javelin'],
    position: [672, 0],
  },
  oneArmed: {
    name: 'oneArmed',
    nameText: 'One-Armed',
    texts: [
      `${green('+200%')} Attack Speed`,
      `${green('Damage')} modifications are increased by ${green('100%')}`,
      'You can only equip one weapon at a time',
    ],
    weapons: ['claw', 'thiefDagger', 'ghostAxe', 'lightningShiv', 'scissors', 'cactiClub', 'torch', 'plank', 'hatchet', 'pruner', 'joustingLance', 'doubleBarrelShotgun', 'shredder', 'smg', 'taser', 'revolver', 'icicle', 'shuriken', 'javelin'],
    position: [384, 576],
  },
  bull: {
    name: 'bull',
    nameText: 'Bull',
    texts: [
      `${green('+20')} Max HP`,
      `${green('+15')} HP Regeneration`,
      `${green('+10')} Armor`,
      `${green('HP Regeneration')} modifications are increased by ${green('50%')}`,
      `You explode for ${green('30')} (+300% ${stat('MeleeDamage')} +300% ${stat('RangedDamage')} +300% ${stat('ElementalDamage')}) damage when you take damage`,
      `You can't equip weapons`,
    ],
    weapons: [],
    position: [0, 96],
  },
  soldier: {
    name: 'soldier',
    nameText: 'Soldier',
    texts: [
      `${green('+50% Damage')} while standing still`,
      `${green('+50% Attack Speed')} while standing still`,
      `${green('+10%')} Speed`,
      `${green('+200%')} pickup range`,
      `${green('+15')} knockback`,
      `You can't attack while moving`,
    ],
    weapons: ['knife', 'lightningShiv', 'crossbow', 'doubleBarrelShotgun', 'laserGun', 'pistol', 'shredder', 'revolver', 'smg', 'taser', 'wand', 'icicle', 'flute', 'javelin'],
    position: [672, 480],
  },
  masochist: {
    name: 'masochist',
    nameText: 'Masochist',
    texts: [
      `${green('+5% Damage')} when you take damage until the end of the wave`,
      `${green('+10')} Max HP`,
      `${green('+20')} HP Regeneration`,
      `${green('+8')} Armor`,
      `${red('-100%')} Damage`,
    ],
    weapons: ['rock', 'scissors', 'cactiClub', 'ghostAxe', 'spikyShield', 'sharpTooth', 'torch', 'brick', 'lute', 'sickle', 'doubleBarrelShotgun', 'medicalGun', 'wand', 'sickle'],
    position: [576, 480],
  },
  knight: {
    name: 'knight',
    nameText: 'Knight',
    texts: [
      `${green('+2 Melee Damage')} for every ${green('1 Armor')} you have`,
      `${green('+3')} Armor`,
      `You can't equip ranged weapons`,
      `You can only equip ${red('tier II')} weapons or above`,
      `${red('% Attack Speed')} modifications are reduced by ${red('50%')}`,
      `${red('Harvesting')} modifications are reduced by ${red('80%')}`,
    ],
    weapons: ['sword', 'hammer', 'spear', 'torch', 'joustingLance', 'quarterstaff', 'plank', 'rock', 'fist', 'knife', 'scissors', 'cactiClub', 'mace', 'anchor'],
    position: [96, 480],
  },
  demon: {
    name: 'demon',
    nameText: 'Demon',
    texts: [
      `${green('50%')} of your ${green('Materials')} are converted into ${green('Max HP')} at the end of a wave (${green('13 Materials')} = ${green('1 Max HP')})`,
      'You buy items using Max HP instead of materials',
    ],
    weapons: ['thiefDagger', 'lightningShiv', 'ghostAxe', 'ghostFlint', 'torch', 'chopper', 'sharpTooth', 'wrench', 'spoon', 'ghostScepter', 'wand', 'taser', 'icicle', 'flute'],
    position: [192, 192],
  },
  baby: {
    name: 'baby',
    nameText: 'Baby',
    texts: [
      `${green('+12')} Harvesting`,
      `${green('-20%')} Items Price`,
      `You gain a weapon slot when you level up instead of a stat upgrade (max: ${green('24')})`,
      'You start with one weapon slot',
      'Shop always sell at least one weapon',
      `${red('+130%')} XP required to level up`,
    ],
    weapons: ['fist', 'scissors', 'screwdriver', 'pruner', 'sharpTooth', 'quarterstaff', 'knife', 'stick', 'plank', 'rock', 'wrench', 'hikingPole', 'spoon', 'shuriken', 'taser', 'wand', 'icicle', 'slingshot', 'pistol', 'flute'],
    position: [288, 0],
  },
  vagabond: {
    name: 'vagabond',
    nameText: 'Vagabond',
    texts: [
      'Equipped weapons always contribute to the class bonuses of other equipped weapons',
      `You can't equip two of the same weapon at the same time`,
      `${red('-5')} Armor`,
      `${red('-5%')} Dodge`,
      `${red('Luck')} modifications are reduced by ${red('50%')}`,
      `${red('Harvesting')} modifications are reduced by ${red('50%')}`,
    ],
    weapons: ['cactiClub', 'chopper', 'thiefDagger', 'spear', 'sharpTooth', 'hand', 'claw', 'quarterstaff', 'hatchet', 'plank', 'ghostFlint', 'spikyShield', 'lightningShiv', 'torch', 'lute', 'shuriken', 'crossbow', 'revolver', 'laserGun'],
    position: [192, 672],
  },
  technomage: {
    name: 'technomage',
    nameText: 'Technomage',
    texts: [
      `You start with ${green('2 Turret')}`,
      `${green('+5% Structure attack speed')} for every permanent ${green('1 Elemental Damage')} you have`,
      `${green('+2 Elemental Damage')} for every ${green('1 Structure')} you have`,
      `${red('+75%')} XP required to level up`,
      `${red('Melee Damage')} modifications are reduced by ${red('100%')}`,
      `${red('Ranged Damage')} modifications are reduced by ${red('100%')}`,
    ],
    weapons: ['wrench', 'screwdriver', 'plank', 'torch', 'lightningShiv', 'pruner', 'taser', 'wand', 'icicle'],
    position: [96, 672],
  },
  vampire: {
    name: 'vampire',
    nameText: 'Vampire',
    texts: [
      `${green('+2% Damage')} for every ${green('1%')} of missing health`,
      `${green('+1% Life Steal')} for every ${green('3%')} of missing health`,
      `${green('+1 Armor')} for every ${green('5%')} of missing health`,
      `${red('Max HP')} modifications are reduced by ${red('25%')}`,
      `${red('-60%')} Damage`,
      `${red('-100')} HP Regeneration`,
      `${red('-100')} HP recovered from consumables`,
    ],
    weapons: ['fist', 'claw', 'sharpTooth', 'ghostFlint', 'hatchet', 'knife', 'thiefDagger', 'lightningShiv', 'scissors', 'spikyShield', 'stick', 'torch', 'screwdriver', 'wrench', 'sickle', 'shuriken', 'pistol', 'smg', 'doubleBarrelShotgun', 'medicalGun', 'revolver', 'shredder', 'crossbow'],
    position: [288, 672],
  },
  sailor: {
    name: 'sailor',
    nameText: 'Sailor',
    texts: [
      `${green('+200%')} damage with ${green('Naval')} weapons against cursed enemies`,
      `${purple('+25')} Curse`,
      `${red('-25%')} Damage`,
      `You can only equip ${red('tier II')} weapons or above`,
      `Dodge is capped at ${red('20%')}`,
      `${red('Harvesting')} modifications are reduced by ${red('100%')}`,
    ],
    weapons: ['anchor', 'trident', 'blunderbuss'],
    position: [672, 192],
  },
  curious: {
    name: 'curious',
    nameText: 'Curious',
    texts: [
      `You start with ${green('1 Spyglass')}`,
      `${green('2')} additional loot aliens appear every wave`,
      'All future loot aliens become stronger when you kill a loot alien',
      `${green('+2% XP Gain')} for every different ${green('Item')} you have`,
      `${red('-10% Damage')} for every duplicate item or weapon you have`,
      `${red('+25%')} Enemy health`,
    ],
    weapons: ['brick', 'cactiClub', 'ghostAxe', 'hatchet', 'knife', 'plank', 'rock', 'torch', 'lightningShiv', 'lute', 'pistol', 'doubleBarrelShotgun', 'icicle', 'javelin', 'slingshot'],
    position: [0, 192],
  },
  builder: {
    name: 'builder',
    nameText: 'Builder',
    texts: [
      `You start with ${green("1 Builder's Turret")}`,
      `Every ${green('5')} uncollected materials are converted into ${green('1% Structure attack speed')} and ${green('1 Structure range')} at the end of a wave`,
      `${green('Engineering')} modifications are increased by ${green('50%')}`,
      `${green('+20')} Harvesting`,
      `You can't have structures`,
      `${red('-30%')} pickup range`,
      `${red('Damage')} modifications are reduced by ${red('75%')}`,
    ],
    weapons: ['brick', 'plank', 'javelin', 'doubleBarrelShotgun', 'laserGun', 'medicalGun', 'revolver', 'shredder', 'smg', 'slingshot', 'ghostScepter', 'flute', 'taser', 'wand'],
    position: [576, 0],
  },
  captain: {
    name: 'captain',
    nameText: 'Captain',
    texts: [
      `${green('+60% XP Gain')} for every free weapon slot you have`,
      `${green('+100% Stats Gained')} from level upgrades`,
      `${red('+200%')} XP required to level up`,
      `${red('+2% Enemy health')} at the end of a wave`,
      `${red('+2% Enemy damage')} at the end of a wave`,
    ],
    weapons: ['fist', 'knife', 'hatchet', 'spear', 'ghostAxe', 'ghostFlint', 'chopper', 'quarterstaff', 'torch', 'plank', 'lightningShiv', 'doubleBarrelShotgun', 'smg', 'revolver', 'slingshot', 'shredder', 'javelin'],
    position: [96, 96],
  },
  creature: {
    name: 'creature',
    nameText: 'Creature',
    texts: [
      `Weapon damage additionally scales with ${purple('35% Curse')}`,
      `You start with ${green('1')} cursed ${green('Fish Hook')}`,
      `${purple('+1 Curse')} when you level up`,
      `${red('-10 Range')} at the end of a wave`,
      `${red('-5% XP Gain')} at the end of a wave`,
    ],
    weapons: ['fist', 'claw', 'cactiClub', 'sharpTooth', 'sickle', 'hatchet', 'rock', 'stick', 'spikyShield', 'chopper', 'torch', 'plank', 'smg', 'shredder', 'icicle', 'ghostScepter', 'javelin'],
    position: [480, 96],
  },
  chef: {
    name: 'chef',
    nameText: 'Chef',
    texts: [
      `${green('+35')} Luck`,
      `${green('+200%')} damage from non elemental sources against burning targets`,
      `Consumables explodes for 5x${green('1')} (+100%${stat('ElementalDamage')}) burning damage when picked up`,
      `You start with ${green('1 Scared Sausage')}`,
      `${red('+100%')} Enemy health`,
      `${red('Elemental Damage')} modifications are reduced by ${red('75%')}`,
    ],
    weapons: ['spoon', 'chopper', 'fist', 'knife', 'hatchet', 'stick', 'torch', 'screwdriver', 'wrench', 'plank', 'pruner', 'cactiClub', 'wand'],
    position: [192, 96],
  },
  druid: {
    name: 'druid',
    nameText: 'Druid',
    texts: [
      `${green('+5')} Max HP`,
      `${green('+15')} Luck`,
      'Enemies have a higher chance of dropping fruits',
      `${green('33%')} chance to get ${green('+1 Luck')} when you pick up a fruit`,
      `${red('33%')} of fruits are poisoned and hurt you (ignores Dodge and Armor)`,
      `${red('-100')} HP Regeneration`,
      `${red('-100%')} Life Steal`,
      `${red('Engineering')} modifications are reduced by ${red('50%')}`,
    ],
    weapons: ['fist', 'claw', 'ghostFlint', 'cactiClub', 'rock', 'chopper', 'quarterstaff', 'pruner', 'sickle', 'lute', 'stick', 'spear', 'torch', 'flute', 'slingshot', 'ghostScepter', 'icicle', 'wand', 'javelin'],
    position: [480, 192],
  },
  dwarf: {
    name: 'dwarf',
    nameText: 'Dwarf',
    texts: [
      `${green('+1 Engineering')} when killing at least ${green('6')} enemies with a direct weapon hit`,
      `${green('+1 Melee Damage')} for every permanent ${green('2 Engineering')} you have`,
      `You can't equip ranged weapons`,
      `${red('-20%')} Dodge`,
      `${red('-100%')} Attack Speed`,
      `${red('% Attack Speed')} modifications are reduced by ${red('50%')}`,
    ],
    weapons: ['hammer', 'wrench', 'brick', 'mace'],
    position: [576, 192],
  },
  gangster: {
    name: 'gangster',
    nameText: 'Gangster',
    texts: [
      `Can steal ${green('1')} item per shop`,
      'Stealing from the shop can spawn an elite',
      'All future elites and bosses become stronger when you kill an elite or a boss',
      `${red('+20%')} Items Price`,
      `Can't lock items`,
    ],
    weapons: ['knife', 'thiefDagger', 'lightningShiv', 'pistol', 'revolver', 'smg', 'doubleBarrelShotgun'],
    position: [480, 288],
  },
  diver: {
    name: 'diver',
    nameText: 'Diver',
    texts: [
      `You start with ${green('1 Harpoon Gun')}`,
      `${green('-100% Harpoon Gun')} price`,
      `${green('+200% Crit Damage')} with ${green('Precise')} weapons`,
      `${green('% Crit Chance')} modifications are increased by ${green('25%')}`,
      `${green('+1 HP Regeneration')} for every ${green('2 Melee Damage')} you have`,
      `Enemies take ${green('300%')} more damage for ${green('3')} seconds when hit by ${green('Ranged Damage')}`,
      `${red('-100')} Ranged Damage`,
      `${red('+250%')} Enemy health`,
    ],
    weapons: ['claw', 'thiefDagger', 'knife', 'scissors', 'sharpTooth', 'shuriken'],
    startWeapon: 'harpoonGun',
    position: [288, 192],
  },
  hiker: {
    name: 'hiker',
    nameText: 'Hiker',
    texts: [
      `Earn ${green('5')} materials for every ${green('10')} steps you take during a wave`,
      `${green('+1 Max HP')} for every ${green('80')} steps you take during a wave`,
      `${green('$ Speed')} modifications are increased by ${green('10%')}`,
      `${red('-5%')} Speed`,
      `${red('-50%')} materials dropped`,
    ],
    weapons: ['hikingPole', 'fist', 'hand', 'lute', 'thiefDagger', 'joustingLance', 'stick', 'flute', 'pistol', 'taser'],
    position: [384, 384],
  },
  buccaneer: {
    name: 'buccaneer',
    nameText: 'Buccaneer',
    texts: [
      `Picked up materials have ${green('+100%')} value`,
      'Picking up a material resets the cooldown of all your weapons',
      `${red('-100%')} Attack Speed`,
      `${red('-50%')} materials dropped from enemies`,
    ],
    weapons: ['brick', 'cactiClub', 'rock', 'spear', 'torch', 'doubleBarrelShotgun', 'laserGun', 'shredder', 'icicle', 'flute', 'slingshot', 'crossbow'],
    position: [480, 0],
  },
  ogre: {
    name: 'ogre',
    nameText: 'Ogre',
    texts: [
      `Enemies taking double their max health as damage explode for ${green('15')} (+50%${stat('MaxHP')} ${red('-50%')}${stat('AttackSpeed')}) damage`,
      `${green('+10')} Melee Damage`,
      `You can't equip ranged weapons`,
      `${red('-50%')} Attack Speed`,
      `${red('-10%')} Speed`,
    ],
    weapons: ['fist', 'brick', 'rock', 'plank', 'cactiClub', 'chopper', 'spoon'],
    position: [192, 576],
  },
  romantic: {
    name: 'romantic',
    nameText: 'Romantic',
    texts: [
      `Hitting an enemy that has less than ${green('25%')} health has a ${green('5%')} (50%${stat('MaxHP')}) chance to charm it for ${green('8')} seconds`,
      `${green('+50 Range')} with melee weapons`,
      `${red('-3% Damage')} for every ${purple('5 Curse')} you have`,
      `${red('-1 Armor')} for every ${purple('5 Curse')} you have`,
      `${purple('+1 Curse')} at the end of a wave`,
    ],
    weapons: ['lute', 'chopper', 'fist', 'spoon', 'scissors', 'sharpTooth', 'hatchet', 'cactiClub', 'claw', 'flute', 'doubleBarrelShotgun', 'shuriken', 'slingshot', 'medicalGun', 'smg', 'taser'],
    position: [672, 96],
  },
}

export default characters
