const green = (v) => `<span class="green">${v}</span>`
const red = (v) => `<span class="red">${v}</span>`

const classes = [
  {
    name: 'Blade',
    bonuses: [
      [`${green('+1')} Melee Damage`, `${green('+1')} Life Steal`],
      [`${green('+2')} Melee Damage`, `${green('+2')} Life Steal`],
      [`${green('+3')} Melee Damage`, `${green('+3')} Life Steal`],
      [`${green('+4')} Melee Damage`, `${green('+4')} Life Steal`],
      [`${green('+5')} Melee Damage`, `${green('+5')} Life Steal`],
    ],
    weapons: [
      'Chopper',
      'CircularSaw',
      'Sword',
      'CaptainsSword',
      'Chainsaw',
      'ThunderSword',
      'Excalibur',
    ],
  },
  {
    name: 'Blunt',
    bonuses: [
      [`${green('+1')} Armor`, `${red('-2%')} Speed`],
      [`${green('+1')} Armor`, `${green('+3')} Max HP`, `${red('-4%')} Speed`],
      [`${green('+2')} Armor`, `${green('+3')} Max HP`, `${red('-6%')} Speed`],
      [`${green('+2')} Armor`, `${green('+6')} Max HP`, `${red('-8%')} Speed`],
      [`${green('+3')} Armor`, `${green('+6')} Max HP`, `${red('-10%')} Speed`],
    ],
    weapons: ['Brick', 'Rock', 'Spoon', 'SpikyShield', 'Hammer', 'WarHammer'],
  },
  {
    name: 'Elemental',
    bonuses: [
      [`${green('+1')} Elemental Damage`],
      [`${green('+2')} Elemental Damage`],
      [`${green('+3')} Elemental Damage`],
      [`${green('+4')} Elemental Damage`],
      [`${green('+5')} Elemental Damage`],
    ],
    weapons: [
      'Icicle',
      'LightningShiv',
      'Plank',
      'Taser',
      'Torch',
      'Wand',
      'Fireball',
      'Flamethrower',
      'FlamingBrassKnuckles',
      'ParticleAccelerator',
      'PlasmaSledge',
      'ThunderSword',
    ],
  },
  {
    name: 'Ethereal',
    bonuses: [
      [`${green('+6%')} Dodge`, `${red('-1')} Armor`],
      [`${green('+12%')} Dodge`, `${red('-2')} Armor`],
      [`${green('+18%')} Dodge`, `${red('-3')} Armor`],
      [`${green('+24%')} Dodge`, `${red('-4')} Armor`],
      [`${green('+30%')} Dodge`, `${red('-5')} Armor`],
    ],
    weapons: ['GhostAxe', 'GhostFlint', 'GhostScepter', 'Scythe'],
  },
  {
    name: 'Explosive',
    bonuses: [
      [`${green('+5%')} Explosion Size`],
      [`${green('+10%')} Explosion Size`],
      [`${green('+15%')} Explosion Size`],
      [`${green('+20%')} Explosion Size`],
      [`${green('+25%')} Explosion Size`],
    ],
    weapons: [
      'Plank',
      'Shredder',
      'Fireball',
      'GrenadeLauncher',
      'RocketLauncher',
      'NuclearLauncher',
      'PlasmaSledge',
      'PowerFist',
      'DexTroyer',
    ],
  },
  {
    name: 'Gun',
    bonuses: [
      [`${green('+10')} Range`],
      [`${green('+20')} Range`],
      [`${green('+30')} Range`],
      [`${green('+40')} Range`],
      [`${green('+50')} Range`],
    ],
    weapons: [
      'DoubleBarrelShotgun',
      'LaserGun',
      'MedicalGun',
      'Pistol',
      'Revolver',
      'Shredder',
      'Smg',
      'Blunderbuss',
      'HarpoonGun',
      'Minigun',
      'SniperGun',
      'Obliterator',
      'ChainGun',
    ],
  },
  {
    name: 'Heavy',
    bonuses: [
      [`${green('+5%')} Damage`],
      [`${green('+10%')} Damage`],
      [`${green('+15%')} Damage`],
      [`${green('+20%')} Damage`],
      [`${green('+25%')} Damage`],
    ],
    weapons: [
      'CactiClub',
      'Anchor',
      'Flamethrower',
      'GrenadeLauncher',
      'Hammer',
      'Mace',
      'RocketLauncher',
      'Minigun',
      'NuclearLauncher',
      'Obliterator',
      'WarHammer',
      'ParticleAccelerator',
      'GatlingLaser',
    ],
  },
  {
    name: 'Legendary',
    bonuses: [
      [`${red('-20')} Max HP`],
      [`${red('-40')} Max HP`],
      [`${red('-60')} Max HP`],
      [`${red('-80')} Max HP`],
      [`${red('-100')} Max HP`],
    ],
    weapons: [
      'ChainGun',
      'DexTroyer',
      'Drill',
      'Excalibur',
      'GatlingLaser',
      'Scythe',
    ],
  },
  {
    name: 'Medical',
    bonuses: [
      [`${green('+1')} HP Regeneration`],
      [`${green('+2')} HP Regeneration`],
      [`${green('+3')} HP Regeneration`],
      [`${green('+4')} HP Regeneration`],
      [`${green('+5')} HP Regeneration`],
    ],
    weapons: ['MedicalGun', 'Scissors', 'CircularSaw'],
  },
  {
    name: 'Medieval',
    bonuses: [
      [`${green('+1')} Armor`],
      [`${green('+1')} Armor`, `${green('+3%')} Dodge`],
      [`${green('+2')} Armor`, `${green('+3%')} Dodge`],
      [`${green('+2')} Armor`, `${green('+6%')} Dodge`],
      [`${green('+3')} Armor`, `${green('+6%')} Dodge`],
    ],
    weapons: [
      'Crossbow',
      'JoustingLance',
      'Quarterstaff',
      'SpikyShield',
      'Mace',
      'Sword',
      'Trident',
    ],
  },
  {
    name: 'Musical',
    bonuses: [
      [`${green('+5')} Luck`],
      [`${green('+10')} Luck`],
      [`${green('+15')} Luck`],
      [`${green('+20')} Luck`],
      [`${green('+25')} Luck`],
    ],
    weapons: ['Flute', 'Lute'],
  },
  {
    name: 'Naval',
    bonuses: [
      [`${green('+1')} Curse`],
      [`${green('+2')} Curse`],
      [`${green('+3')} Curse`],
      [`${green('+4')} Curse`],
      [`${green('+5')} Curse`],
    ],
    weapons: [
      'Anchor',
      'Blunderbuss',
      'HarpoonGun',
      'Trident',
      'CaptainsSword',
    ],
  },
  {
    name: 'Precise',
    bonuses: [
      [`${green('+3%')} Crit Chance`],
      [`${green('+6%')} Crit Chance`],
      [`${green('+9%')} Crit Chance`],
      [`${green('+12%')} Crit Chance`],
      [`${green('+15%')} Crit Chance`],
    ],
    weapons: [
      'Claw',
      'Crossbow',
      'Icicle',
      'Knife',
      'LightningShiv',
      'Scissors',
      'SharpTooth',
      'Shuriken',
      'ThiefDagger',
      'SniperGun',
      'Drill',
    ],
  },
  {
    name: 'Primitive',
    bonuses: [
      [`${green('+3')} Max HP`],
      [`${green('+6')} Max HP`],
      [`${green('+9')} Max HP`],
      [`${green('+12')} Max HP`],
      [`${green('+15')} Max HP`],
    ],
    weapons: [
      'CactiClub',
      'Hatchet',
      'Javelin',
      'Quarterstaff',
      'Rock',
      'SharpTooth',
      'Slingshot',
      'Spear',
      'Stick',
      'Torch',
    ],
  },
  {
    name: 'Support',
    bonuses: [
      [`${green('+5')} Harvesting`],
      [`${green('+10')} Harvesting`],
      [`${green('+15')} Harvesting`],
      [`${green('+20')} Harvesting`],
      [`${green('+25')} Harvesting`],
    ],
    weapons: [
      'Hand',
      'HikingPole',
      'Lute',
      'Pruner',
      'Sickle',
      'Taser',
      'PotatoThrower',
    ],
  },
  {
    name: 'Tool',
    bonuses: [
      [`${green('+1')} Engineering`],
      [`${green('+2')} Engineering`],
      [`${green('+3')} Engineering`],
      [`${green('+4')} Engineering`],
      [`${green('+5')} Engineering`],
    ],
    weapons: ['Screwdriver', 'Wrench', 'Chainsaw'],
  },
  {
    name: 'Unarmed',
    bonuses: [
      [`${green('+3%')} Dodge`],
      [`${green('+6%')} Dodge`],
      [`${green('+9%')} Dodge`],
      [`${green('+12%')} Dodge`],
      [`${green('+15%')} Dodge`],
    ],
    weapons: ['Claw', 'Fist', 'Hand', 'FlamingBrassKnuckles', 'PowerFist'],
  },
]

export default classes
