const green = (v) => `<span class="green">${v}</span>`
const purple = (v) => `<span class="purple">${v}</span>`
const red = (v) => `<span class="red">${v}</span>`
const stat = (v) => `<span class="stat ${v}"></span>`

const items = {
  acid: {
    name: 'acid',
    nameText: 'Acid',
    tier: 2,
    effect: `${green('+8')} Max HP<br/>${red('-2%')} Dodge<br/>${red('-2')} Knockback`,
    price: 65,
    limit: 0,
    tags: ['maxHP'],
    position: [0, 0],
  },
  adrenaline: {
    name: 'adrenaline',
    nameText: 'Adrenaline',
    tier: 3,
    effect:
      `${green('+5%')} Dodge<br/>${green('50%')} chance to heal ${green('5')} HP when dodging an attack`,
    price: 60,
    limit: 1,
    tags: ['dodge'],
    position: [60, 0],
  },
  alienBaby: {
    name: 'alienBaby',
    nameText: 'Alien Baby',
    tier: 3,
    effect: `${green('+15')} Max HP<br/>${green('+10%')} Enemy health`,
    price: 80,
    limit: 0,
    tags: ['maxHP'],
    position: [120, 0],
  },
  alienEyes: {
    name: 'alienEyes',
    nameText: 'Alien Eyes',
    tier: 2,
    effect:
      `Shoots ${green('6')} alien eyes around you every ${green('3')} seconds dealing ${green('6')} (<span>+50%${stat('maxHP')}) damage each</span>`,
    price: 50,
    limit: 0,
    tags: ['maxHP'],
    position: [180, 0],
  },
  alienMagic: {
    name: 'alienMagic',
    nameText: 'Alien Magic',
    tier: 3,
    effect:
      `${green('+8')} Max HP<br/>${green('+3')} HP Regeneration<br/>${red('-8')} Luck`,
    price: 85,
    limit: 0,
    tags: ['maxHP', 'hpRegeneration'],
    position: [240, 0],
  },
  alienTongue: {
    name: 'alienTongue',
    nameText: 'Alien Tongue',
    tier: 1,
    effect: `${green('+30%')} pickup range<br/>${green('+1')} Knockback`,
    price: 25,
    limit: 0,
    tags: ['pickup', 'knockback'],
    position: [300, 0],
  },
  alienWorm: {
    name: 'alienWorm',
    nameText: 'Alien Worm',
    tier: 1,
    effect:
      `${green('+3')} Max HP<br/>${green('+2')} HP Regeneration<br/>${red('-1')} HP recovered from consumables`,
    price: 15,
    limit: 0,
    tags: ['maxHP', 'hpRegeneration'],
    position: [360, 0],
  },
  alloy: {
    name: 'alloy',
    nameText: 'Alloy',
    tier: 3,
    effect:
      `${green('+3')} Melee Damage<br/>${green('+3')} Ranged Damage<br/>${green('+3')} Elemental Damage<br/>${green('+3')} Engineering<br/>${green('+5%')} Crit Chance<br/>${red('-6%')} Dodge`,
    price: 80,
    limit: 0,
    tags: [
      'meleeDamage',
      'rangedDamage',
      'engineering',
      'critChance',
      'elementalDamage',
    ],
    position: [420, 0],
  },
  anvil: {
    name: 'anvil',
    nameText: 'Anvil',
    tier: 4,
    effect:
      `A random weapon is upgraded when entering a shop. If you have no weapon to upgrade, you gain ${green('+2')} <span>Armor</span> instead.`,
    price: 120,
    limit: 1,
    tags: [],
    position: [480, 0],
  },
  ashes: {
    name: 'ashes',
    nameText: 'Ashes',
    tier: 4,
    effect:
      `${green('+20%')} Damage<br/>${green('+20%')} Attack Speed<br/>${green('+100')} Range<br/>${red('-1')} <span>Armor</span> at the end of a wave`,
    price: 100,
    limit: 0,
    tags: ['attackSpeed', 'damage', 'range'],
    position: [540, 0],
  },
  axolotl: {
    name: 'axolotl',
    nameText: 'Axolotl',
    tier: 4,
    effect:
      `Your highest (<span>Max HP</span>) and lowest (<span>Max HP</span>) positive primary stats are swapped when you get this item`,
    price: 130,
    limit: 1,
    tags: [],
    position: [600, 0],
  },
  babyElephant: {
    name: 'babyElephant',
    nameText: 'Baby Elephant',
    tier: 1,
    effect:
      `${green('25%')} chance to deal ${green('1')} (<span>25%${stat('luck')}) damage to a random enemy when you pick up a material</span>`,
    price: 22,
    limit: 0,
    tags: ['luck', 'pickup'],
    position: [660, 0],
  },
  babyGecko: {
    name: 'babyGecko',
    nameText: 'Baby Gecko',
    tier: 1,
    effect:
      `${green('+10')} Range<br/>${green('+25%')} chance to instantly attract a material when it’s dropped`,
    price: 18,
    limit: 4,
    tags: ['pickup', 'range'],
    position: [720, 0],
  },
  babySquid: {
    name: 'babySquid',
    nameText: 'Baby Squid',
    tier: 2,
    effect:
      `${green('+1')} HP Regeneration when you level up<br/>${red('-3%')} Attack Speed`,
    price: 55,
    limit: 0,
    tags: ['hpRegeneration'],
    position: [780, 0],
  },
  babyWithABeard: {
    name: 'babyWithABeard',
    nameText: 'Baby with a Beard',
    tier: 3,
    effect:
      `One bullet dealing ${green('1')} (<span>+100%${stat('rangedDamage')}) damage is fired from an enemy corpse when they die<br/>${red('-50')} Range</span>`,
    price: 100,
    limit: 0,
    tags: ['rangedDamage'],
    position: [0, 60],
  },
  bag: {
    name: 'bag',
    nameText: 'Bag',
    tier: 1,
    effect:
      `${green('+15')} materials when you pick up a crate<br/>${red('-1%')} Speed`,
    price: 15,
    limit: 3,
    tags: ['luck', 'exploration', 'economy'],
    position: [60, 60],
  },
  bait: {
    name: 'bait',
    nameText: 'Bait',
    tier: 2,
    effect:
      `${green('+8%')} Damage<br/>Special enemies appear at the beginning of the next wave`,
    price: 25,
    limit: 0,
    tags: ['damage'],
    position: [120, 60],
  },
  ballAndChain: {
    name: 'ballAndChain',
    nameText: 'Ball and Chain',
    tier: 3,
    effect:
      `${green('+15%')} Damage<br/>${green('+3')} Armor<br/>${green('+5')} Knockback<br/>${red('-3%')} Speed<br/>Weapons have a minimum cooldown of <span>0.75</span> seconds between attacks`,
    price: 75,
    limit: 1,
    tags: ['damage', 'armor', 'knockback'],
    position: [180, 60],
  },
  bandana: {
    name: 'bandana',
    nameText: 'Bandana',
    tier: 3,
    effect:
      `Projectiles pierce through ${green('1')} additional target<br/>${red('-10%')} Damage`,
    price: 75,
    limit: 0,
    tags: ['rangedDamage'],
    position: [240, 60],
  },
  banner: {
    name: 'banner',
    nameText: 'Banner',
    tier: 2,
    effect:
      `${green('+20')} Range<br/>${green('+10%')} Attack Speed<br/>${red('-5')} Knockback`,
    price: 55,
    limit: 0,
    tags: ['range', 'attackSpeed'],
    position: [300, 60],
  },
  barnacle: {
    name: 'barnacle',
    nameText: 'Barnacle',
    tier: 3,
    effect:
      `${green('+35%')} stats gained from level upgrades<br/>${purple('+1 Curse')} when you level up`,
    price: 80,
    limit: 1,
    tags: ['curse', 'xpGain'],
    position: [360, 60],
  },
  barricade: {
    name: 'barricade',
    nameText: 'Barricade',
    tier: 3,
    effect:
      `${green('+3')} Knockback<br/>${green('+8')} <span>Armor</span> while standing still<br/>${red('-5%')} Speed`,
    price: 75,
    limit: 0,
    tags: ['armor', 'standStill', 'knockback'],
    position: [420, 60],
  },
  bat: {
    name: 'bat',
    nameText: 'Bat',
    tier: 1,
    effect: `${green('+2%')} Life Steal<br/>${red('-2')} Harvesting`,
    price: 20,
    limit: 0,
    tags: ['lifeSteal'],
    position: [480, 60],
  },
  beanTeacher: {
    name: 'beanTeacher',
    nameText: 'Bean Teacher',
    tier: 3,
    effect: `${green('+50%')} XP Gain<br/>${red('-2%')} Life Steal`,
    price: 70,
    limit: 0,
    tags: ['xpGain'],
    position: [540, 60],
  },
  beanie: {
    name: 'beanie',
    nameText: 'Beanie',
    tier: 1,
    effect: `${green('+4%')} Speed<br/>${red('-6')} Range`,
    price: 20,
    limit: 0,
    tags: ['speed'],
    position: [600, 60],
  },
  bigArms: {
    name: 'bigArms',
    nameText: 'Big Arms',
    tier: 4,
    effect:
      `${green('+12')} Melee Damage<br/>${green('+6')} Ranged Damage<br/>${green('+3')} Knockback<br/>${red('-3%')} Attack Speed<br/>${red('-3%')} Speed`,
    price: 105,
    limit: 0,
    tags: ['meleeDamage', 'rangedDamage', 'knockback'],
    position: [660, 60],
  },
  blackBelt: {
    name: 'blackBelt',
    nameText: 'Black Belt',
    tier: 2,
    effect:
      `${green('+25%')} XP Gain<br/>${green('+3')} Melee Damage<br/>${green('+3')} Knockback<br/>${red('-8')} Luck`,
    price: 50,
    limit: 0,
    tags: ['meleeDamage', 'xpGain', 'knockback'],
    position: [720, 60],
  },
  blackFlag: {
    name: 'blackFlag',
    nameText: 'Black Flag',
    tier: 3,
    effect:
      `${green('+1')} material when you kill a cursed enemy<br/>+10% Enemies<br/>${green('+10%')} Enemy health<br/>${green('+10%')} Enemy damage<br/>${purple('+5 Curse')}`,
    price: 60,
    limit: 1,
    tags: ['curse', 'moreEnemies'],
    position: [780, 60],
  },
  blindfold: {
    name: 'blindfold',
    nameText: 'Blindfold',
    tier: 2,
    effect:
      `${green('+5%')} Crit Chance<br/>${green('+5%')} Dodge<br/>${red('-15')} Range`,
    price: 45,
    limit: 0,
    tags: ['critChance', 'dodge'],
    position: [0, 120],
  },
  bloodDonation: {
    name: 'bloodDonation',
    nameText: 'Blood Donation',
    tier: 3,
    effect:
      `${green('+40')} Harvesting<br/>You take ${green('1')} damage per second (does not give invulnerability time)`,
    price: 50,
    limit: 0,
    tags: ['harvesting'],
    position: [60, 120],
  },
  bloodLeech: {
    name: 'bloodLeech',
    nameText: 'Blood Leech',
    tier: 2,
    effect:
      `${green('+2%')} Life Steal<br/>${green('+2')} HP Regeneration<br/>${red('-3')} Harvesting`,
    price: 45,
    limit: 0,
    tags: ['lifeSteal', 'hpRegeneration'],
    position: [120, 120],
  },
  bloodyHand: {
    name: 'bloodyHand',
    nameText: 'Bloody Hand',
    tier: 4,
    effect:
      `${green('+10%')} Life Steal<br/>${green('+2%')} Damage for every ${green('1%')} Life Steal you have <br/>You take ${green('1')} damage per second (does not give invulnerability time)`,
    price: 110,
    limit: 1,
    tags: ['lifeSteal'],
    position: [180, 120],
  },
  boilingWater: {
    name: 'boilingWater',
    nameText: 'Boiling Water',
    tier: 1,
    effect: `${green('+2')} Elemental Damage<br/>${red('-1')} Max HP`,
    price: 30,
    limit: 0,
    tags: ['elementalDamage'],
    position: [240, 120],
  },
  boneDice: {
    name: 'boneDice',
    nameText: 'Bone Dice',
    tier: 2,
    effect:
      `${green('+50%')} chance to get ${green('+1%')} Damage when rerolling in the shop<br/>${green('+10%')} chance to get ${red('-1')} <span>Max HP</span> when rerolling in the shop`,
    price: 30,
    limit: 2,
    tags: ['damage'],
    position: [300, 120],
  },
  book: {
    name: 'book',
    nameText: 'Book',
    tier: 1,
    effect: `${green('+1')} Engineering`,
    price: 8,
    limit: 0,
    tags: ['engineering'],
    position: [360, 120],
  },
  bowlerHat: {
    name: 'bowlerHat',
    nameText: 'Bowler Hat',
    tier: 3,
    effect:
      `${green('+15')} Luck<br/>${green('+18')} Harvesting<br/>${red('-5%')} Attack Speed<br/>${red('-3%')} Crit Chance`,
    price: 75,
    limit: 0,
    tags: ['luck', 'harvesting'],
    position: [420, 120],
  },
  boxingGlove: {
    name: 'boxingGlove',
    nameText: 'Boxing Glove',
    tier: 1,
    effect: `${green('+1')} Melee Damage<br/>${green('+3')} Knockback`,
    price: 18,
    limit: 0,
    tags: ['meleeDamage', 'knockback'],
    position: [480, 120],
  },
  brokenMouth: {
    name: 'brokenMouth',
    nameText: 'Broken Mouth',
    tier: 1,
    effect: `${green('+5')} Max HP<br/>${red('-1')} HP Regeneration`,
    price: 25,
    limit: 0,
    tags: ['maxHP'],
    position: [540, 120],
  },
  butterfly: {
    name: 'butterfly',
    nameText: 'Butterfly',
    tier: 1,
    effect: `${green('+2%')} Life Steal<br/>${red('-1')} Elemental Damage`,
    price: 30,
    limit: 0,
    tags: ['lifeSteal'],
    position: [600, 120],
  },
  cake: {
    name: 'cake',
    nameText: 'Cake',
    tier: 1,
    effect: `${green('+3')} Max HP<br/>${red('-1%')} Damage`,
    price: 15,
    limit: 0,
    tags: ['maxHP'],
    position: [660, 120],
  },
  campfire: {
    name: 'campfire',
    nameText: 'Campfire',
    tier: 2,
    effect:
      `${green('+2')} Elemental Damage<br/>${green('+2')} HP Regeneration<br/>${red('-2%')} Speed`,
    price: 40,
    limit: 0,
    tags: ['elementalDamage', 'hpRegeneration'],
    position: [720, 120],
  },
  candle: {
    name: 'candle',
    nameText: 'Candle',
    tier: 3,
    effect:
      `${green('+4')} Elemental Damage<br/>${green('+1')} HP Regeneration<br/>-10% Enemies<br/>${red('-5%')} Damage`,
    price: 65,
    limit: 1,
    tags: ['elementalDamage', 'hpRegeneration', 'lessEnemies'],
    position: [780, 120],
  },
  cape: {
    name: 'cape',
    nameText: 'Cape',
    tier: 4,
    effect:
      `${green('+5%')} Life Steal<br/>${green('+20%')} Dodge<br/>${red('-2')} Melee Damage<br/>${red('-2')} Ranged Damage<br/>${red('-2')} Elemental Damage`,
    price: 110,
    limit: 0,
    tags: ['lifeSteal', 'dodge'],
    position: [0, 180],
  },
  cauldron: {
    name: 'cauldron',
    nameText: 'Cauldron',
    tier: 2,
    effect:
      `${green('+50%')} pickup range<br/>${green('+20%')} Damage for ${green('2')} seconds after picking up a consumable<br/>${red('-2')} HP Regeneration`,
    price: 35,
    limit: 1,
    tags: ['pickup'],
    position: [60, 180],
  },
  celeryTea: {
    name: 'celeryTea',
    nameText: 'Celery Tea',
    tier: 2,
    effect:
      `${green('+5%')} XP Gain at the end of a wave<br/>${green('+50%')} XP Gain during the next wave<br/>${green('+100%')} Enemy health during the next wave`,
    price: 35,
    limit: 0,
    tags: ['xpGain'],
    position: [120, 180],
  },
  chameleon: {
    name: 'chameleon',
    nameText: 'Chameleon',
    tier: 3,
    effect:
      `${green('+3%')} Dodge<br/>${green('+20%')} Dodge while standing still<br/>${red('-4%')} Damage`,
    price: 70,
    limit: 0,
    tags: ['dodge', 'standStill'],
    position: [180, 180],
  },
  charcoal: {
    name: 'charcoal',
    nameText: 'Charcoal',
    tier: 1,
    effect:
      `${green('+1')} Elemental Damage<br/>${green('+2')} Melee Damage<br/>${red('-2')} Harvesting`,
    price: 20,
    limit: 0,
    tags: ['elementalDamage', 'meleeDamage'],
    position: [240, 180],
  },
  clawTree: {
    name: 'clawTree',
    nameText: 'Claw Tree',
    tier: 1,
    effect:
      `${green('+1')} Melee Damage<br/>${green('+3%')} Crit Chance<br/>${red('-1')} Max HP`,
    price: 20,
    limit: 0,
    tags: ['meleeDamage', 'critChance'],
    position: [300, 180],
  },
  clockworkWasp: {
    name: 'clockworkWasp',
    nameText: 'Clockwork Wasp',
    tier: 2,
    effect: `${green('+10%')} Structure attack speed<br/>${green('+5%')} Speed`,
    price: 45,
    limit: 0,
    tags: ['structure', 'speed'],
    position: [360, 180],
  },
  clover: {
    name: 'clover',
    nameText: 'Clover',
    tier: 3,
    effect:
      `${green('+20')} Luck<br/>${green('+6%')} Dodge<br/>${red('-2%')} Life Steal`,
    price: 65,
    limit: 0,
    tags: ['luck', 'dodge'],
    position: [420, 180],
  },
  coffee: {
    name: 'coffee',
    nameText: 'Coffee',
    tier: 1,
    effect: `${green('+10%')} Attack Speed<br/>${red('-2%')} Damage`,
    price: 20,
    limit: 0,
    tags: ['attackSpeed'],
    position: [480, 180],
  },
  cog: {
    name: 'cog',
    nameText: 'Cog',
    tier: 2,
    effect:
      `${green('+4')} Engineering<br/>${green('+1')} Knockback<br/>${red('-4%')} Damage`,
    price: 35,
    limit: 0,
    tags: ['engineering', 'knockback'],
    position: [540, 180],
  },
  coil: {
    name: 'coil',
    nameText: 'Coil',
    tier: 3,
    effect:
      `${green('+5')} Knockback<br/>${green('+1%')} Damage for every ${green('1')} <span>Knockback</span> you have`,
    price: 70,
    limit: 3,
    tags: ['damage', 'knockback'],
    position: [600, 180],
  },
  communitySupport: {
    name: 'communitySupport',
    nameText: 'Community Support',
    tier: 3,
    effect:
      `${green('+1%')} Attack Speed for every current living enemy <br/>${red('-2')} Armor`,
    price: 75,
    limit: 1,
    tags: ['attackSpeed'],
    position: [660, 180],
  },
  compass: {
    name: 'compass',
    nameText: 'Compass',
    tier: 2,
    effect:
      `${green('+5%')} Speed<br/>${green('+3')} Engineering<br/>${red('-3%')} Crit Chance`,
    price: 40,
    limit: 0,
    tags: ['speed', 'engineering'],
    position: [720, 180],
  },
  coral: {
    name: 'coral',
    nameText: 'Coral',
    tier: 2,
    effect:
      `${green('+10')} HP Regeneration while standing still<br/>${red('-10')} Range`,
    price: 40,
    limit: 0,
    tags: ['hpRegeneration', 'standStill'],
    position: [780, 180],
  },
  corruptedShard: {
    name: 'corruptedShard',
    nameText: 'Corrupted Shard',
    tier: 1,
    effect:
      `${green('+3%')} Damage<br/>${purple('+1 Curse')}`,
    price: 12,
    limit: 0,
    tags: ['damage', 'curse'],
    position: [0, 240],
  },
  coupon: {
    name: 'coupon',
    nameText: 'Coupon',
    tier: 1,
    effect: `${red('-5%')} Items Price`,
    price: 15,
    limit: 5,
    tags: ['economy'],
    position: [60, 240],
  },
  crown: {
    name: 'crown',
    nameText: 'Crown',
    tier: 3,
    effect:
      `Harvesting increases by an additional ${green('8%')} at the end of a wave`,
    price: 70,
    limit: 1,
    tags: ['harvesting'],
    position: [120, 240],
  },
  crystal: {
    name: 'crystal',
    nameText: 'Crystal',
    tier: 3,
    effect:
      `${green('+5%')} Attack Speed<br/>${green('+1%')} Attack Speed every 1 second until the end of the wave<br/>Bonus is lost when taking damage<br/>${red('-2')} Engineering`,
    price: 65,
    limit: 0,
    tags: ['attackSpeed'],
    position: [180, 240],
  },
  cuteMonkey: {
    name: 'cuteMonkey',
    nameText: 'Cute Monkey',
    tier: 1,
    effect:
      `${green('+8%')} chance to heal ${green('1')} HP when picking up a material<br/>${red('-1')} Ranged Damage`,
    price: 25,
    limit: 13,
    tags: ['pickup'],
    position: [240, 240],
  },
  cyberball: {
    name: 'cyberball',
    nameText: 'Cyberball',
    tier: 2,
    effect:
      `${green('25%')} chance to deal ${green('1')} (<span>25%${stat('luck')}) damage to a random enemy when an enemy dies</span>`,
    price: 30,
    limit: 0,
    tags: ['luck'],
    position: [300, 240],
  },
  cyclopsWorm: {
    name: 'cyclopsWorm',
    nameText: 'Cyclops Worm',
    tier: 2,
    effect: `${green('+12%')} Damage<br/>${red('-12')} Range`,
    price: 45,
    limit: 0,
    tags: ['damage'],
    position: [360, 240],
  },
  dangerousBunny: {
    name: 'dangerousBunny',
    nameText: 'Dangerous Bunny',
    tier: 2,
    effect: `${green('+1')} free reroll in the shop`,
    price: 30,
    limit: 3,
    tags: ['economy'],
    position: [420, 240],
  },
  decomposingFlesh: {
    name: 'decomposingFlesh',
    nameText: 'Decomposing Flesh',
    tier: 2,
    effect:
      `${green('+1%')} Life Steal when you level up<br/>${red('-1')} <span>Max HP</span> when you level up`,
    price: 30,
    limit: 0,
    tags: ['lifeSteal'],
    position: [480, 240],
  },
  defectiveSteroids: {
    name: 'defectiveSteroids',
    nameText: 'Defective Steroids',
    tier: 1,
    effect:
      `${green('+2')} Max HP<br/>${green('+2')} Melee Damage<br/>${red('-3%')} Attack Speed`,
    price: 20,
    limit: 0,
    tags: ['maxHP', 'meleeDamage'],
    position: [540, 240],
  },
  diploma: {
    name: 'diploma',
    nameText: 'Diploma',
    tier: 4,
    effect:
      `${green('+10')} Engineering<br/>${green('+50%')} XP Gain<br/>${red('-3')} Max HP`,
    price: 90,
    limit: 0,
    tags: ['engineering', 'xpGain'],
    position: [600, 240],
  },
  ductTape: {
    name: 'ductTape',
    nameText: 'Duct Tape',
    tier: 1,
    effect:
      `${green('+1')} Armor<br/>${green('+1')} Engineering<br/>${red('-2')} Max HP`,
    price: 20,
    limit: 0,
    tags: ['armor', 'engineering'],
    position: [660, 240],
  },
  dynamite: {
    name: 'dynamite',
    nameText: 'Dynamite',
    tier: 1,
    effect: `${green('+15%')} Explosion Damage`,
    price: 20,
    limit: 0,
    tags: ['explosive'],
    position: [720, 240],
  },
  energyBracelet: {
    name: 'energyBracelet',
    nameText: 'Energy Bracelet',
    tier: 2,
    effect:
      `${green('+4%')} Crit Chance<br/>${green('+2')} Elemental Damage<br/>${red('-2')} Ranged Damage`,
    price: 55,
    limit: 0,
    tags: ['critChance', 'elementalDamage'],
    position: [780, 240],
  },
  estysCouch: {
    name: 'estysCouch',
    nameText: "Esty's Couch",
    tier: 4,
    effect:
      `${green('+5')} Max HP<br/>${green('+2')} HP Regeneration for every permanent ${red('-1%')} Speed you have <br/>${red('-20%')} Speed`,
    price: 100,
    limit: 1,
    tags: ['hpRegeneration', 'maxHP'],
    position: [0, 300],
  },
  exoskeleton: {
    name: 'exoskeleton',
    nameText: 'Exoskeleton',
    tier: 4,
    effect:
      `${green('+3')} Armor<br/>${green('+5%')} Crit Chance<br/>${green('+5')} Engineering<br/>${green('+5%')} Speed<br/>${red('-2')} HP Regeneration<br/>${red('-2%')} Life Steal`,
    price: 90,
    limit: 0,
    tags: ['armor', 'critChance', 'engineering', 'speed'],
    position: [60, 300],
  },
  explosiveShells: {
    name: 'explosiveShells',
    nameText: 'Explosive Shells',
    tier: 4,
    effect:
      `${green('+60%')} Explosion Damage<br/>${green('+15%')} Explosion Size<br/>${red('-15%')} Damage`,
    price: 100,
    limit: 0,
    tags: ['explosive'],
    position: [120, 300],
  },
  explosiveTurret: {
    name: 'explosiveTurret',
    nameText: 'Explosive Turret',
    tier: 4,
    effect:
      `Spawns a turret that shoots explosive bullets dealing ${green('25')} (<span>+150%${stat('engineering')}) damage in an area</span>`,
    price: 80,
    limit: 0,
    tags: ['engineering', 'structure'],
    position: [180, 300],
  },
  extraStomach: {
    name: 'extraStomach',
    nameText: 'Extra Stomach',
    tier: 4,
    effect:
      `${green('+1')} <span>Max HP</span> when picking up a consumable while at maximum health (max ${green('+8')} per wave)`,
    price: 100,
    limit: 1,
    tags: ['maxHP', 'luck'],
    position: [240, 300],
  },
  eyepatch: {
    name: 'eyepatch',
    nameText: 'Eyepatch',
    tier: 2,
    effect:
      `Projectiles get ${green('+1')} piercing on critical hit<br/>${green('+3%')} Crit Chance<br/>${red('-10%')} Accuracy`,
    price: 55,
    limit: 0,
    tags: ['critChance', 'rangedDamage'],
    position: [300, 300],
  },
  eyesSurgery: {
    name: 'eyesSurgery',
    nameText: 'Eyes Surgery',
    tier: 2,
    effect:
      `Burning activates ${green('20%')} faster<br/>${green('+1')} Elemental Damage<br/>${red('-10')} Range`,
    price: 60,
    limit: 2,
    tags: ['elementalDamage'],
    position: [360, 300],
  },
  fertilizer: {
    name: 'fertilizer',
    nameText: 'Fertilizer',
    tier: 1,
    effect: `${green('+8')} Harvesting<br/>${red('-1')} Melee Damage`,
    price: 15,
    limit: 0,
    tags: ['harvesting'],
    position: [540, 300],
  },
  fairy: {
    name: 'fairy',
    nameText: 'Fairy',
    tier: 3,
    effect:
      `${green('+1')} HP Regeneration for every different <span>Tier I item</span> you have <br/>${red('-3')} HP Regeneration for every different <span>Tier IV item</span> you have`,
    price: 85,
    limit: 1,
    tags: ['hpRegeneration'],
    position: [420, 300],
  },
  feather: {
    name: 'feather',
    nameText: 'Feather',
    tier: 1,
    effect:
      `${green('+1')} Ranged Damage<br/>${green('+3%')} Dodge<br/>${red('-3%')} XP Gain`,
    price: 18,
    limit: 0,
    tags: ['rangedDamage', 'dodge'],
    position: [480, 300],
  },
  fin: {
    name: 'fin',
    nameText: 'Fin',
    tier: 3,
    effect:
      `${green('+10%')} Speed<br/>${green('+3%')} Life Steal<br/>${red('-8')} Luck`,
    price: 65,
    limit: 0,
    tags: ['speed', 'lifeSteal'],
    position: [600, 300],
  },
  fishHook: {
    name: 'fishHook',
    nameText: 'Fish Hook',
    tier: 2,
    effect:
      `Locked items and weapons have a ${green('20%')} chance to become cursed when leaving the shop<br/>${purple('+1 Curse')}`,
    price: 35,
    limit: 3,
    tags: ['curse', 'lock'],
    position: [660, 300],
  },
  focus: {
    name: 'focus',
    nameText: 'Focus',
    tier: 4,
    effect:
      `${green('+30%')} Damage<br/>${red('-3%')} Attack Speed for every different weapon you have`,
    price: 110,
    limit: 0,
    tags: ['damage'],
    position: [720, 300],
  },
  friedRice: {
    name: 'friedRice',
    nameText: 'Fried Rice',
    tier: 3,
    effect:
      `${green('+1')} HP Regeneration for every currently burning enemy`,
    price: 60,
    limit: 1,
    tags: ['hpRegeneration'],
    position: [780, 300],
  },
  frozenHeart: {
    name: 'frozenHeart',
    nameText: 'Frozen Heart',
    tier: 3,
    effect:
      `${green('+8')} Elemental Damage<br/>${green('+5%')} Crit Chance<br/>Weapon damage additionally scales with ${green('10%')} <span>Elemental Damage</span><br/>Burning activates ${green('100%')} slower`,
    price: 90,
    limit: 1,
    tags: ['elementalDamage', 'critChance'],
    position: [0, 360],
  },
  fuelTank: {
    name: 'fuelTank',
    nameText: 'Fuel Tank',
    tier: 2,
    effect:
      `${green('+4')} Elemental Damage<br/>${red('-1')} Melee Damage<br/>${red('-1')} Ranged Damage`,
    price: 45,
    limit: 0,
    tags: ['elementalDamage'],
    position: [60, 360],
  },
  gamblingToken: {
    name: 'gamblingToken',
    nameText: 'Gambling Token',
    tier: 2,
    effect: `${green('+8%')} Dodge<br/>${red('-1')} Armor`,
    price: 50,
    limit: 0,
    tags: ['dodge'],
    position: [120, 360],
  },
  garden: {
    name: 'garden',
    nameText: 'Garden',
    tier: 2,
    effect: `Spawns a garden that creates a fruit every ${green('15')} seconds`,
    price: 50,
    limit: 0,
    tags: ['consumable', 'structure'],
    position: [180, 360],
  },
  gentleAlien: {
    name: 'gentleAlien',
    nameText: 'Gentle Alien',
    tier: 1,
    effect: `${green('+2')} Max HP<br/>${green('+5%')} Damage<br/>+5% Enemies`,
    price: 30,
    limit: 10,
    tags: ['maxHP', 'damage', 'moreEnemies'],
    position: [240, 360],
  },
  giantBelt: {
    name: 'giantBelt',
    nameText: 'Giant Belt',
    tier: 4,
    effect:
      `Critical hits deal ${green('10%')} of an enemy’s current health as bonus damage (${green('1%')} for bosses and elites)`,
    price: 110,
    limit: 1,
    tags: ['critChance'],
    position: [300, 360],
  },
  glassCannon: {
    name: 'glassCannon',
    nameText: 'Glass Cannon',
    tier: 3,
    effect: `${green('+25%')} Damage<br/>${red('-3')} Armor`,
    price: 75,
    limit: 0,
    tags: ['damage'],
    position: [360, 360],
  },
  glasses: {
    name: 'glasses',
    nameText: 'Glasses',
    tier: 1,
    effect: `${green('+20')} Range`,
    price: 20,
    limit: 0,
    tags: ['range'],
    position: [420, 360],
  },
  gnome: {
    name: 'gnome',
    nameText: 'Gnome',
    tier: 4,
    effect:
      `${green('+10')} Melee Damage<br/>${green('+10')} Elemental Damage<br/>${red('-20')} Range<br/>${red('-20%')} pickup range`,
    price: 100,
    limit: 0,
    tags: ['meleeDamage', 'elementalDamage'],
    position: [480, 360],
  },
  goatSkull: {
    name: 'goatSkull',
    nameText: 'Goat Skull',
    tier: 1,
    effect: `${green('+3')} Melee Damage<br/>${red('-2%')} Crit Chance`,
    price: 25,
    limit: 0,
    tags: ['meleeDamage'],
    position: [540, 360],
  },
  goblet: {
    name: 'goblet',
    nameText: 'Goblet',
    tier: 3,
    effect:
      `${green('+15%')} chance to heal 1 HP when killing an enemy<br/>${red('-3')} HP Regeneration`,
    price: 70,
    limit: 3,
    tags: [],
    position: [600, 360],
  },
  goldfish: {
    name: 'goldfish',
    nameText: 'Goldfish',
    tier: 3,
    effect: `Items will be ${green('1')} tier higher after the next reroll`,
    price: 23,
    limit: 0,
    tags: [],
    position: [660, 360],
  },
  greekFire: {
    name: 'greekFire',
    nameText: 'Greek Fire',
    tier: 4,
    effect:
      `Burning deals an additional ${green('10%')} of current enemy HP as damage (${green('1%')} for bosses and elites)`,
    price: 100,
    limit: 1,
    tags: ['elementalDamage'],
    position: [720, 360],
  },
  grindsMagicalLeaf: {
    name: 'grindsMagicalLeaf',
    nameText: "Grind's Magical Leaf",
    tier: 4,
    effect:
      `${green('+3')} <span>Max HP</span> at the end of a wave<br/>${green('+1')} HP Regeneration at the end of a wave<br/>${green('+1%')} Life Steal at the end of a wave`,
    price: 110,
    limit: 0,
    tags: ['maxHP', 'hpRegeneration', 'lifeSteal'],
    position: [780, 360],
  },
  gummyBerserker: {
    name: 'gummyBerserker',
    nameText: 'Gummy Berserker',
    tier: 1,
    effect:
      `${green('+5%')} Attack Speed<br/>${green('+25')} Range<br/>${red('-1')} Armor`,
    price: 25,
    limit: 0,
    tags: ['attackSpeed', 'range'],
    position: [0, 420],
  },
  handcuffs: {
    name: 'handcuffs',
    nameText: 'Handcuffs',
    tier: 3,
    effect:
      `${green('+8')} Melee Damage<br/>${green('+8')} Ranged Damage<br/>${green('+8')} Elemental Damage<br/>Your Max HP is capped at its current value`,
    price: 80,
    limit: 1,
    tags: ['meleeDamage', 'rangedDamage', 'elementalDamage'],
    position: [60, 420],
  },
  headInjury: {
    name: 'headInjury',
    nameText: 'Head Injury',
    tier: 1,
    effect: `${green('+6%')} Damage<br/>${red('-8')} Range`,
    price: 25,
    limit: 0,
    tags: ['damage'],
    position: [120, 420],
  },
  heavyBullets: {
    name: 'heavyBullets',
    nameText: 'Heavy Bullets',
    tier: 4,
    effect:
      `${green('+5')} Ranged Damage<br/>${green('+10%')} Damage<br/>${green('+10')} Range<br/>${red('-5%')} Attack Speed<br/>${red('-5%')} Crit Chance`,
    price: 100,
    limit: 0,
    tags: ['rangedDamage', 'damage', 'range'],
    position: [180, 420],
  },
  hedgehog: {
    name: 'hedgehog',
    nameText: 'Hedgehog',
    tier: 1,
    effect:
      `${green('+2')} Melee Damage<br/>${green('+1')} Ranged Damage<br/>${red('-1')} HP Regeneration`,
    price: 30,
    limit: 0,
    tags: ['meleeDamage', 'rangedDamage'],
    position: [240, 420],
  },
  helmet: {
    name: 'helmet',
    nameText: 'Helmet',
    tier: 1,
    effect: `${green('+1')} Armor<br/>${red('-2%')} Speed`,
    price: 15,
    limit: 0,
    tags: ['armor'],
    position: [300, 420],
  },
  honey: {
    name: 'honey',
    nameText: 'Honey',
    tier: 3,
    effect:
      `${green('+3')} Ranged Damage<br/>${green('+10%')} Explosion Damage<br/>${green('+5%')} Explosion Size<br/>${red('-3%')} Speed<br/>${red('-3%')} Dodge`,
    price: 70,
    limit: 0,
    tags: ['rangedDamage', 'explosive'],
    position: [360, 420],
  },
  huntingTrophy: {
    name: 'huntingTrophy',
    nameText: 'Hunting Trophy',
    tier: 3,
    effect:
      `${green('33%')} chance to gain ${green('1')} material when killing an enemy with a critical hit`,
    price: 55,
    limit: 3,
    tags: ['critChance'],
    position: [420, 420],
  },
  iceCube: {
    name: 'iceCube',
    nameText: 'Ice Cube',
    tier: 2,
    effect:
      `Enemies take ${green('10%')} more damage for ${green('3')} seconds when first hit by <span>Elemental Damage</span>`,
    price: 50,
    limit: 1,
    tags: ['elementalDamage'],
    position: [480, 420],
  },
  improvedTools: {
    name: 'improvedTools',
    nameText: 'Improved Tools',
    tier: 3,
    effect:
      `${green('+10%')} Attack Speed<br/>Increases the attack speed of your structures by 0% (<span>50%${stat('attackSpeed')}</span>)`,
    price: 70,
    limit: 1,
    tags: ['structure', 'attackSpeed'],
    position: [540, 420],
  },
  incendiaryTurret: {
    name: 'incendiaryTurret',
    nameText: 'Incendiary Turret',
    tier: 2,
    effect:
      `Spawns a turret that shoots flames dealing 8x${green('5')} (<span>+33%${stat('engineering')}) burning damage</span>`,
    price: 40,
    limit: 0,
    tags: ['engineering', 'structure'],
    position: [600, 420],
  },
  injection: {
    name: 'injection',
    nameText: 'Injection',
    tier: 1,
    effect: `${green('+7%')} Damage<br/>${red('-2')} Max HP`,
    price: 20,
    limit: 0,
    tags: ['damage'],
    position: [660, 420],
  },
  insanity: {
    name: 'insanity',
    nameText: 'Insanity',
    tier: 1,
    effect: `${green('+6%')} Crit Chance<br/>${red('-3%')} Damage`,
    price: 20,
    limit: 0,
    tags: ['critChance'],
    position: [720, 420],
  },
  jelly: {
    name: 'jelly',
    nameText: 'Jelly',
    tier: 1,
    effect:
      `${green('+1')} <span>Max HP</span> for every different weapon you have`,
    price: 15,
    limit: 0,
    tags: ['maxHP'],
    position: [780, 420],
  },
  jerky: {
    name: 'jerky',
    nameText: 'Jerky',
    tier: 2,
    effect:
      `${green('+3')} HP recovered from consumables<br/>Consumables heal you over ${green('4')} seconds instead of instantly`,
    price: 50,
    limit: 1,
    tags: ['consumable'],
    position: [0, 480],
  },
  jetPack: {
    name: 'jetPack',
    nameText: 'Jet Pack',
    tier: 4,
    effect:
      `${green('+15%')} Speed<br/>${green('+10%')} Dodge<br/>${red('-5')} Max HP<br/>${red('-1')} Armor`,
    price: 100,
    limit: 0,
    tags: ['speed', 'dodge'],
    position: [60, 480],
  },
  knot: {
    name: 'knot',
    nameText: 'Knot',
    tier: 3,
    effect:
      `${green('+15%')} Damage<br/>${green('+15')} Max HP<br/>Weapons can no longer be upgraded or recycled`,
    price: 80,
    limit: 1,
    tags: ['damage', 'maxHP'],
    position: [120, 480],
  },
  krakensEye: {
    name: 'krakensEye',
    nameText: "Kraken's Eye",
    tier: 4,
    effect:
      `You have a ${green('50%')} chance to explode for ${green('10')} (<span>+500%${stat('curse')}</span>) damage when you get hit<br/>${green('+10')} Max HP<br/>${purple('+10 Curse')}`,
    price: 110,
    limit: 1,
    tags: ['explosive', 'maxHP', 'curse'],
    position: [180, 480],
  },
  landmines: {
    name: 'landmines',
    nameText: 'Landmines',
    tier: 1,
    effect:
      `A landmine spawns every ${green('12')} seconds dealing ${green('10')} (<span>+100%${stat('engineering')}) damage in an area</span>`,
    price: 15,
    limit: 0,
    tags: ['engineering', 'explosive', 'structure'],
    position: [240, 480],
  },
  lantern: {
    name: 'lantern',
    nameText: 'Lantern',
    tier: 4,
    effect:
      `${green('+10%')} Damage<br/>${green('+50')} Range<br/>${green('+15')} Knockback<br/>Knocks nearby enemies back every ${green('3')} seconds`,
    price: 100,
    limit: 1,
    tags: ['damage', 'range', 'knockback'],
    position: [300, 480],
  },
  laserTurret: {
    name: 'laserTurret',
    nameText: 'Laser Turret',
    tier: 3,
    effect:
      `Spawns a turret that shoots piercing bullets dealing ${green('20')} (<span>+125%${stat('engineering')}) damage</span>`,
    price: 65,
    limit: 0,
    tags: ['engineering', 'structure'],
    position: [360, 480],
  },
  leatherVest: {
    name: 'leatherVest',
    nameText: 'Leather Vest',
    tier: 2,
    effect: `${green('+2')} Armor<br/>${green('+6%')} Dodge<br/>${red('-3')} Max HP`,
    price: 45,
    limit: 0,
    tags: ['armor', 'dodge'],
    position: [420, 480],
  },
  lemonade: {
    name: 'lemonade',
    nameText: 'Lemonade',
    tier: 1,
    effect: `${green('+1')} HP recovered from consumables`,
    price: 15,
    limit: 0,
    tags: ['consumable'],
    position: [480, 480],
  },
  lens: {
    name: 'lens',
    nameText: 'Lens',
    tier: 1,
    effect: `${green('+1')} Ranged Damage<br/>${red('-5')} Range`,
    price: 20,
    limit: 0,
    tags: ['rangedDamage'],
    position: [540, 480],
  },
  lighthouse: {
    name: 'lighthouse',
    nameText: 'Lighthouse',
    tier: 3,
    effect:
      `${green('+20')} Engineering<br/>${red('-1')} <span>Engineering</span> for every ${green('1')} <span>Structure</span> you have`,
    price: 80,
    limit: 1,
    tags: ['engineering'],
    position: [600, 480],
  },
  littleFrog: {
    name: 'littleFrog',
    nameText: 'Little Frog',
    tier: 2,
    effect:
      `${green('+20%')} pickup range<br/>${green('+10')} Harvesting<br/>${red('-3%')} Dodge`,
    price: 45,
    limit: 0,
    tags: ['harvesting', 'pickup'],
    position: [660, 480],
  },
  littleMuscleyDude: {
    name: 'littleMuscleyDude',
    nameText: 'Little Muscley Dude',
    tier: 2,
    effect:
      `${green('+3')} Melee Damage<br/>${green('+5')} Max HP<br/>${red('-15')} Range`,
    price: 50,
    limit: 0,
    tags: ['meleeDamage', 'maxHP'],
    position: [720, 480],
  },
  lostDuck: {
    name: 'lostDuck',
    nameText: 'Lost Duck',
    tier: 1,
    effect: `${green('+8')} Luck<br/>${red('-1')} Elemental Damage`,
    price: 25,
    limit: 0,
    tags: ['luck'],
    position: [780, 480],
  },
  luckyCharm: {
    name: 'luckyCharm',
    nameText: 'Lucky Charm',
    tier: 3,
    effect:
      `${green('+30')} Luck<br/>${red('-2')} Melee Damage<br/>${red('-1')} Ranged Damage`,
    price: 75,
    limit: 0,
    tags: ['luck'],
    position: [0, 540],
  },
  luckyCoin: {
    name: 'luckyCoin',
    nameText: 'Lucky Coin',
    tier: 4,
    effect:
      `${green('+2')} Luck for every ${green('1%')} Crit Chance you have <br/>${red('-2')} Armor`,
    price: 105,
    limit: 1,
    tags: ['critChance', 'luck'],
    position: [60, 540],
  },
  lure: {
    name: 'lure',
    nameText: 'Lure',
    tier: 2,
    effect:
      `${green('+2')} HP Regeneration<br/>${green('2')} additional loot aliens appear during the next wave`,
    price: 34,
    limit: 0,
    tags: ['hpRegeneration'],
    position: [180, 540],
  },
  lumberjackShirt: {
    name: 'lumberjackShirt',
    nameText: 'Lumberjack Shirt',
    tier: 1,
    effect: `Trees die in one hit`,
    price: 15,
    limit: 1,
    tags: ['exploration'],
    position: [120, 540],
  },
  mammoth: {
    name: 'mammoth',
    nameText: 'Mammoth',
    tier: 4,
    effect:
      `${green('+20')} Melee Damage<br/>${green('+5')} HP Regeneration<br/>${green('+5')} Knockback<br/>${red('-8%')} Damage<br/>${red('-3%')} Speed`,
    price: 110,
    limit: 0,
    tags: ['meleeDamage', 'hpRegeneration', 'knockback'],
    position: [240, 540],
  },
  mastery: {
    name: 'mastery',
    nameText: 'Mastery',
    tier: 2,
    effect: `${green('+6')} Melee Damage<br/>${red('-3')} Ranged Damage`,
    price: 55,
    limit: 0,
    tags: ['meleeDamage'],
    position: [300, 540],
  },
  medal: {
    name: 'medal',
    nameText: 'Medal',
    tier: 2,
    effect:
      `${green('+3')} Max HP<br/>${green('+3%')} Damage<br/>${green('+1')} Armor<br/>${green('+3%')} Speed<br/>${red('-4%')} Crit Chance`,
    price: 55,
    limit: 0,
    tags: ['maxHP', 'damage', 'armor', 'speed'],
    position: [360, 540],
  },
  medicalTurret: {
    name: 'medicalTurret',
    nameText: 'Medical Turret',
    tier: 2,
    effect:
      `Spawns a medical turret that shoots bullets healing ${green('3')} (<span>+5%${stat('engineering')}) HP</span>`,
    price: 40,
    limit: 0,
    tags: ['engineering', 'structure'],
    position: [420, 540],
  },
  medikit: {
    name: 'medikit',
    nameText: 'Medikit',
    tier: 4,
    effect:
      `${green('+10')} HP Regeneration<br/>${green('+2')} HP Regeneration every 5 seconds until the end of the wave<br/>${red('-10')} Luck`,
    price: 95,
    limit: 0,
    tags: ['hpRegeneration'],
    position: [480, 540],
  },
  metalDetector: {
    name: 'metalDetector',
    nameText: 'Metal Detector',
    tier: 2,
    effect:
      `${green('+5%')} chance to double the value of picked up materials<br/>${green('+6')} Luck<br/>${green('+2')} Engineering<br/>${red('-5%')} Damage`,
    price: 40,
    limit: 20,
    tags: ['luck', 'engineering', 'pickup', 'economy'],
    position: [540, 540],
  },
  metalPlate: {
    name: 'metalPlate',
    nameText: 'Metal Plate',
    tier: 2,
    effect: `${green('+2')} Armor<br/>${red('-3%')} Damage`,
    price: 40,
    limit: 0,
    tags: ['armor'],
    position: [600, 540],
  },
  mirror: {
    name: 'mirror',
    nameText: 'Mirror',
    tier: 3,
    effect:
      `Duplicates the next item you get from the shop (item limits can't be exceeded)`,
    price: 60,
    limit: 0,
    tags: [],
    position: [660, 540],
  },
  missile: {
    name: 'missile',
    nameText: 'Missile',
    tier: 2,
    effect: `${green('+10%')} Damage<br/>${red('-4%')} Attack Speed`,
    price: 45,
    limit: 0,
    tags: ['damage'],
    position: [720, 540],
  },
  mouse: {
    name: 'mouse',
    nameText: 'Mouse',
    tier: 3,
    effect: `${green('+5%')} Life Steal<br/>+10% Enemies<br/>${red('-5')} Harvesting`,
    price: 55,
    limit: 5,
    tags: ['lifeSteal', 'moreEnemies'],
    position: [780, 540],
  },
  mushroom: {
    name: 'mushroom',
    nameText: 'Mushroom',
    tier: 1,
    effect: `${green('+3')} HP Regeneration<br/>${red('-2')} Luck`,
    price: 25,
    limit: 0,
    tags: ['hpRegeneration'],
    position: [0, 600],
  },
  mutation: {
    name: 'mutation',
    nameText: 'Mutation',
    tier: 1,
    effect:
      `${green('+1')} Ranged Damage<br/>${green('+1')} Elemental Damage<br/>${red('-3')} Knockback`,
    price: 25,
    limit: 0,
    tags: ['rangedDamage', 'elementalDamage'],
    position: [60, 600],
  },
  nail: {
    name: 'nail',
    nameText: 'Nail',
    tier: 3,
    effect:
      `${green('+5')} Engineering<br/>Weapon damage additionally scales with ${green('20%')} <span>Engineering</span><br/>${red('-2')} Ranged Damage`,
    price: 65,
    limit: 1,
    tags: ['engineering'],
    position: [120, 600],
  },
  nightGoggles: {
    name: 'nightGoggles',
    nameText: 'Night Goggles',
    tier: 4,
    effect:
      `${green('+15%')} Crit Chance<br/>${green('+50')} Range<br/>${red('-3')} Max HP<br/>${red('-1')} Armor`,
    price: 95,
    limit: 0,
    tags: ['critChance', 'range'],
    position: [180, 600],
  },
  octopus: {
    name: 'octopus',
    nameText: 'Octopus',
    tier: 4,
    effect:
      `${green('+12')} Max HP<br/>${green('+5')} HP Regeneration<br/>${green('+3%')} Life Steal<br/>${red('-8%')} Crit Chance`,
    price: 105,
    limit: 0,
    tags: ['maxHP', 'lifeSteal', 'hpRegeneration'],
    position: [240, 600],
  },
  padding: {
    name: 'padding',
    nameText: 'Padding',
    tier: 2,
    effect:
      `${green('+3')} Max HP<br/>${green('+1')} <span>Max HP</span> for every ${green('80')} <span>Materials</span> you have`,
    price: 45,
    limit: 1,
    tags: ['maxHP'],
    position: [300, 600],
  },
  panda: {
    name: 'panda',
    nameText: 'Panda',
    tier: 4,
    effect: `${green('+12')} Max HP<br/>${green('+25')} Luck<br/>${red('-5%')} Damage`,
    price: 100,
    limit: 0,
    tags: ['maxHP', 'luck'],
    position: [360, 600],
  },
  peacefulBee: {
    name: 'peacefulBee',
    nameText: 'Peaceful Bee',
    tier: 1,
    effect:
      `${green('+4%')} Dodge<br/>${green('+4')} Harvesting<br/>${red('-1')} Melee Damage<br/>${red('-1')} Ranged Damage`,
    price: 18,
    limit: 0,
    tags: ['dodge', 'harvesting'],
    position: [420, 600],
  },
  peacock: {
    name: 'peacock',
    nameText: 'Peacock',
    tier: 3,
    effect:
      `${green('+25%')} XP Gain<br/>${green('+100%')} XP Gain during the next wave<br/>${green('+50')} <span>% Enemy damage</span> during the next wave`,
    price: 50,
    limit: 0,
    tags: ['xpGain'],
    position: [480, 600],
  },
  pearl: {
    name: 'pearl',
    nameText: 'Pearl',
    tier: 2,
    effect:
      `${green('+1%')} Damage for every permanent ${green('10')} Luck you have <br/>${green('+3%')} chance of finding an extra <span>Pearl</span> in a crate`,
    price: 60,
    limit: 20,
    tags: ['luck'],
    position: [540, 600],
  },
  pencil: {
    name: 'pencil',
    nameText: 'Pencil',
    tier: 1,
    effect:
      `${green('+2')} Engineering<br/>${red('-1%')} Attack Speed<br/>${red('-1%')} Crit Chance`,
    price: 15,
    limit: 0,
    tags: ['engineering'],
    position: [600, 600],
  },
  penguin: {
    name: 'penguin',
    nameText: 'Penguin',
    tier: 1,
    effect:
      `${green('+1')} HP Regeneration<br/>${green('+1')} HP Regeneration until the end of the wave when picking up a consumable while at maximum health`,
    price: 25,
    limit: 3,
    tags: ['hpRegeneration'],
    position: [660, 600],
  },
  piggyBank: {
    name: 'piggyBank',
    nameText: 'Piggy Bank',
    tier: 2,
    effect:
      `${green('+20%')} of your materials at the start of waves (stops working at wave 20)`,
    price: 40,
    limit: 1,
    tags: [],
    position: [720, 600],
  },
  pileOfBooks: {
    name: 'pileOfBooks',
    nameText: 'Pile of Books',
    tier: 3,
    effect:
      `Your structures can crit<br/>${green('+3%')} Crit Chance<br/>${green('+3')} Engineering`,
    price: 70,
    limit: 1,
    tags: ['critChance', 'engineering'],
    position: [780, 600],
  },
  plant: {
    name: 'plant',
    nameText: 'Plant',
    tier: 1,
    effect: `${green('+3')} HP Regeneration<br/>${red('-1%')} Life Steal`,
    price: 15,
    limit: 0,
    tags: ['hpRegeneration'],
    position: [0, 660],
  },
  plasticExplosive: {
    name: 'plasticExplosive',
    nameText: 'Plastic Explosive',
    tier: 3,
    effect: `${green('+25%')} Explosion Size`,
    price: 60,
    limit: 0,
    tags: ['explosive'],
    position: [60, 660],
  },
  poisonousTonic: {
    name: 'poisonousTonic',
    nameText: 'Poisonous Tonic',
    tier: 3,
    effect:
      `${green('+10%')} Attack Speed<br/>${green('+5%')} Crit Chance<br/>${green('+15')} Range<br/>${red('-2')} HP Regeneration`,
    price: 80,
    limit: 0,
    tags: ['attackSpeed', 'critChance', 'range'],
    position: [180, 660],
  },
  pocketFactory: {
    name: 'pocketFactory',
    nameText: 'Pocket Factory',
    tier: 2,
    effect: `${green('+2')} Engineering<br/>Killing a tree spawns a turret`,
    price: 75,
    limit: 1,
    tags: ['engineering', 'exploration', 'structure'],
    position: [120, 660],
  },
  potato: {
    name: 'potato',
    nameText: 'Potato',
    tier: 4,
    effect:
      `${green('+3')} Max HP<br/>${green('+2')} HP Regeneration<br/>${green('+1%')} Life Steal<br/>${green('+5%')} Damage<br/>${green('+5%')} Attack Speed<br/>${green('+3%')} Speed<br/>${green('+3%')} Dodge<br/>${green('+1')} Armor<br/>${green('+5')} Luck`,
    price: 95,
    limit: 0,
    tags: ['maxHP', 'hpRegeneration', 'damage', 'speed', 'luck'],
    position: [240, 660],
  },
  powerGenerator: {
    name: 'powerGenerator',
    nameText: 'Power Generator',
    tier: 3,
    effect:
      `${green('+1%')} Damage for every permanent ${green('1%')} Speed you have <br/>${red('-5%')} Damage`,
    price: 65,
    limit: 1,
    tags: ['speed', 'damage'],
    position: [300, 660],
  },
  propellerHat: {
    name: 'propellerHat',
    nameText: 'Propeller Hat',
    tier: 1,
    effect: `${green('+10')} Luck<br/>${red('-2%')} Damage`,
    price: 28,
    limit: 0,
    tags: ['luck'],
    position: [360, 660],
  },
  pumpkin: {
    name: 'pumpkin',
    nameText: 'Pumpkin',
    tier: 2,
    effect:
      `${green('+15%')} Piercing Damage. Can't go above base damage<br/>${red('-2%')} Damage`,
    price: 40,
    limit: 0,
    tags: ['rangedDamage'],
    position: [420, 660],
  },
  recyclingMachine: {
    name: 'recyclingMachine',
    nameText: 'Recycling Machine',
    tier: 2,
    effect: `Gain ${green('35%')} more materials from recycling items`,
    price: 35,
    limit: 1,
    tags: ['economy'],
    position: [480, 660],
  },
  regenerationPotion: {
    name: 'regenerationPotion',
    nameText: 'Regeneration Potion',
    tier: 4,
    effect:
      `HP Regeneration is doubled when you have less than ${green('50%')} health<br/>${green('+3')} HP Regeneration`,
    price: 90,
    limit: 1,
    tags: ['hpRegeneration'],
    position: [540, 660],
  },
  reinforcedSteel: {
    name: 'reinforcedSteel',
    nameText: 'Reinforced Steel',
    tier: 2,
    effect:
      `${green('+2')} Ranged Damage<br/>${green('+3')} Engineering<br/>${red('-3%')} Speed`,
    price: 50,
    limit: 0,
    tags: ['rangedDamage', 'engineering'],
    position: [600, 660],
  },
  retromationsHoodie: {
    name: 'retromationsHoodie',
    nameText: "Retromation's Hoodie",
    tier: 4,
    effect:
      `${green('+2%')} Attack Speed for every ${green('1%')} Dodge you have <br/>${red('-80')} Range`,
    price: 110,
    limit: 1,
    tags: ['dodge'],
    position: [660, 660],
  },
  ricochet: {
    name: 'ricochet',
    nameText: 'Ricochet',
    tier: 4,
    effect: `Your projectiles gain ${green('+1')} bounce<br/>${red('-25%')} Damage`,
    price: 110,
    limit: 0,
    tags: ['rangedDamage'],
    position: [720, 660],
  },
  ripAndTear: {
    name: 'ripAndTear',
    nameText: 'Rip and Tear',
    tier: 3,
    effect:
      `Enemies have a ${green('20%')} chance to explode for ${green('10')} (<span>+50%${stat('meleeDamage')}</span>) damage when they die<br/>${red('-5%')} Crit Chance`,
    price: 65,
    limit: 5,
    tags: ['meleeDamage', 'explosive'],
    position: [780, 660],
  },
  riposte: {
    name: 'riposte',
    nameText: 'Riposte',
    tier: 2,
    effect:
      `${green('+2')} Melee Damage<br/>${green('100%')} chance to deal ${green('1')} (<span>300%${stat('meleeDamage')}</span>) damage to an enemy when dodging their attack`,
    price: 40,
    limit: 0,
    tags: ['dodge', 'meleeDamage'],
    position: [0, 720],
  },
  ritual: {
    name: 'ritual',
    nameText: 'Ritual',
    tier: 2,
    effect:
      `${green('+6%')} Damage<br/>${green('+2%')} Life Steal<br/>${red('-2')} Engineering`,
    price: 60,
    limit: 0,
    tags: ['damage', 'lifeSteal'],
    position: [60, 720],
  },
  robotArm: {
    name: 'robotArm',
    nameText: 'Robot Arm',
    tier: 4,
    effect:
      `${green('+3')} <span>Melee Damage</span> at the end of a wave<br/>${green('+3')} <span>Engineering</span> at the end of a wave<br/>${red('-1')} <span>Max HP</span> at the end of a wave`,
    price: 100,
    limit: 0,
    tags: ['meleeDamage', 'engineering'],
    position: [120, 720],
  },
  sadTomato: {
    name: 'sadTomato',
    nameText: 'Sad Tomato',
    tier: 3,
    effect: `${green('+8')} HP Regeneration<br/>Start waves with ${red('-50%')} HP`,
    price: 50,
    limit: 1,
    tags: ['hpRegeneration'],
    position: [180, 720],
  },
  saltwater: {
    name: 'saltwater',
    nameText: 'Saltwater',
    tier: 2,
    effect:
      `${green('+2')} Melee Damage<br/>${green('+3%')} Attack Speed<br/>${green('+10%')} Speed for ${green('3')} seconds when you take damage<br/>${red('-1')} Elemental Damage`,
    price: 50,
    limit: 1,
    tags: ['meleeDamage', 'attackSpeed', 'speed'],
    position: [240, 720],
  },
  scar: {
    name: 'scar',
    nameText: 'Scar',
    tier: 1,
    effect: `${green('+20%')} XP Gain<br/>${red('-8')} Range`,
    price: 25,
    limit: 0,
    tags: ['xpGain'],
    position: [300, 720],
  },
  scaredSausage: {
    name: 'scaredSausage',
    nameText: 'Scared Sausage',
    tier: 1,
    effect:
      `Attacks have a ${green('25%')} chance to deal 3x${green('1')} (<span>+100%${stat('elementalDamage')}</span>) burning damage`,
    price: 25,
    limit: 4,
    tags: ['elementalDamage'],
    position: [360, 720],
  },
  scarf: {
    name: 'scarf',
    nameText: 'Scarf',
    tier: 3,
    effect:
      `${green('+4')} HP Regeneration<br/>${green('+4')} Melee Damage<br/>${green('+4%')} Speed<br/>${green('+25')} <span>% Enemy Speed</span> during the next wave`,
    price: 80,
    limit: 0,
    tags: ['hpRegeneration', 'meleeDamage', 'speed'],
    position: [420, 720],
  },
  scope: {
    name: 'scope',
    nameText: 'Scope',
    tier: 2,
    effect:
      `${green('+2')} Ranged Damage<br/>${green('+25')} Range<br/>${red('-7%')} Attack Speed`,
    price: 48,
    limit: 0,
    tags: ['rangedDamage', 'range'],
    position: [480, 720],
  },
  seashell: {
    name: 'seashell',
    nameText: 'Seashell',
    tier: 4,
    effect:
      `Every ranged weapon's 5th projectile has ${green('+3')} projectiles<br/>${red('-10%')} Damage`,
    price: 100,
    limit: 1,
    tags: ['rangedDamage'],
    position: [540, 720],
  },
  shackles: {
    name: 'shackles',
    nameText: 'Shackles',
    tier: 3,
    effect:
      `${green('+8')} HP Regeneration<br/>${green('+8')} Engineering<br/>${green('+80')} Range<br/>Your Speed is capped at its current value`,
    price: 80,
    limit: 1,
    tags: ['range', 'hpRegeneration', 'engineering'],
    position: [600, 720],
  },
  shadyPotion: {
    name: 'shadyPotion',
    nameText: 'Shady Potion',
    tier: 2,
    effect: `${green('+20')} Luck<br/>${red('-2')} HP Regeneration`,
    price: 48,
    limit: 0,
    tags: ['luck'],
    position: [660, 720],
  },
  sharpBullet: {
    name: 'sharpBullet',
    nameText: 'Sharp Bullet',
    tier: 1,
    effect:
      `Projectiles pierce through ${green('1')} additional target<br/>${red('-20%')} Piercing Damage<br/>${red('-5%')} Damage<br/>${red('-3')} Knockback`,
    price: 25,
    limit: 1,
    tags: ['rangedDamage'],
    position: [720, 720],
  },
  shmoop: {
    name: 'shmoop',
    nameText: 'Shmoop',
    tier: 3,
    effect:
      `${green('+6')} Max HP<br/>${green('+2')} HP Regeneration<br/>${red('-2')} Melee Damage<br/>${red('-1')} Ranged Damage`,
    price: 60,
    limit: 0,
    tags: ['maxHP', 'hpRegeneration'],
    position: [780, 720],
  },
  sifdsRelic: {
    name: 'sifdsRelic',
    nameText: "Sifd's Relic",
    tier: 4,
    effect:
      `${green('+3')} Armor<br/>${green('+100%')} chance to instantly attract a material when it’s dropped`,
    price: 100,
    limit: 1,
    tags: ['pickup', 'armor'],
    position: [0, 780],
  },
  silverBullet: {
    name: 'silverBullet',
    nameText: 'Silver Bullet',
    tier: 3,
    effect: `${green('+25%')} damage against bosses and elites`,
    price: 70,
    limit: 0,
    tags: ['damage'],
    position: [60, 780],
  },
  smallFish: {
    name: 'smallFish',
    nameText: 'Small Fish',
    tier: 1,
    effect:
      `${green('+10%')} damage against targets above ${green('75%')} health<br/>${red('-3%')} Attack Speed`,
    price: 18,
    limit: 0,
    tags: ['damage'],
    position: [120, 780],
  },
  smallMagazine: {
    name: 'smallMagazine',
    nameText: 'Small Magazine',
    tier: 2,
    effect:
      `${green('+2')} Ranged Damage<br/>${green('+10%')} Attack Speed<br/>${red('-6%')} Damage`,
    price: 60,
    limit: 0,
    tags: ['rangedDamage', 'attackSpeed'],
    position: [180, 780],
  },
  snail: {
    name: 'snail',
    nameText: 'Snail',
    tier: 2,
    effect: `${red('-8%')} Enemy Speed<br/>${red('-3%')} Speed`,
    price: 40,
    limit: 1,
    tags: ['lessEnemySpeed'],
    position: [240, 780],
  },
  snake: {
    name: 'snake',
    nameText: 'Snake',
    tier: 1,
    effect:
      `Burning spreads to an additional nearby enemy<br/>${red('-1')} Max HP`,
    price: 25,
    limit: 0,
    tags: ['elementalDamage'],
    position: [300, 780],
  },
  snowball: {
    name: 'snowball',
    nameText: 'Snowball',
    tier: 2,
    effect:
      `${green('+1')} <span>Elemental Damage</span> every time you get an item that increases <span>Elemental Damage</span>`,
    price: 50,
    limit: 1,
    tags: ['elementalDamage'],
    position: [360, 780],
  },
  spicySauce: {
    name: 'spicySauce',
    nameText: 'Spicy Sauce',
    tier: 2,
    effect:
      `${green('+3')} Max HP<br/>Consumables have a ${green('33%')} chance to explode for ${green('10')} (<span>+100%${stat('maxHP')}) damage when picked up</span>`,
    price: 40,
    limit: 3,
    tags: ['maxHP', 'luck', 'explosive'],
    position: [420, 780],
  },
  spider: {
    name: 'spider',
    nameText: 'Spider',
    tier: 4,
    effect:
      `${green('+12%')} Damage<br/>${green('+6%')} Attack Speed for every different weapon you have <br/>${red('-3%')} Dodge<br/>${red('-5')} Harvesting`,
    price: 110,
    limit: 0,
    tags: ['damage', 'attackSpeed'],
    position: [480, 780],
  },
  spyglass: {
    name: 'spyglass',
    nameText: 'Spyglass',
    tier: 2,
    effect: `${green('+10')} Range<br/>${red('-25%')} Reroll Price`,
    price: 30,
    limit: 2,
    tags: ['range'],
    position: [540, 780],
  },
  starfish: {
    name: 'starfish',
    nameText: 'Starfish',
    tier: 3,
    effect:
      `${green('+20%')} materials dropped from enemies<br/>${green('+10')} Harvesting<br/>${red('+15%')} Enemy damage`,
    price: 75,
    limit: 3,
    tags: ['harvesting'],
    position: [600, 780],
  },
  statue: {
    name: 'statue',
    nameText: 'Statue',
    tier: 3,
    effect:
      `${green('+40%')} Attack Speed while standing still<br/>${red('-10%')} Speed`,
    price: 60,
    limit: 0,
    tags: ['attackSpeed', 'standStill'],
    position: [660, 780],
  },
  strangeBook: {
    name: 'strangeBook',
    nameText: 'Strange Book',
    tier: 3,
    effect:
      `${green('+1')} <span>Engineering</span> for every permanent ${green('1')} <span>Elemental Damage</span> you have <br/>${red('-1')} Melee Damage<br/>${red('-1')} Ranged Damage`,
    price: 70,
    limit: 1,
    tags: ['engineering', 'elementalDamage'],
    position: [780, 780],
  },
  stoneSkin: {
    name: 'stoneSkin',
    nameText: 'Stone Skin',
    tier: 3,
    effect:
      `${green('+1')} <span>Max HP</span> for every permanent ${green('1')} <span>Armor</span> you have <br/>${red('-6%')} Attack Speed`,
    price: 85,
    limit: 1,
    tags: ['armor', 'maxHP'],
    position: [720, 780],
  },
  sunglasses: {
    name: 'sunglasses',
    nameText: 'Sunglasses',
    tier: 2,
    effect: `${green('+10%')} Crit Chance<br/>${red('-1')} Armor`,
    price: 50,
    limit: 0,
    tags: ['critChance'],
    position: [840, 0],
  },
  sunkenBell: {
    name: 'sunkenBell',
    nameText: 'Sunken Bell',
    tier: 3,
    effect:
      `Once per wave, you explode for ${green('100')} (<span>+500%${stat('meleeDamage')}+500%${stat('rangedDamage')}+500%${stat('elementalDamage')}+500%${stat('engineering')}) damage when you fall below ${green('40%')} health</span>`,
    price: 65,
    limit: 1,
    tags: ['explosive'],
    position: [840, 60],
  },
  tardigrade: {
    name: 'tardigrade',
    nameText: 'Tardigrade',
    tier: 3,
    effect: `Nullifies the damage of one hit taken every wave`,
    price: 50,
    limit: 0,
    tags: [],
    position: [840, 120],
  },
  tentacle: {
    name: 'tentacle',
    nameText: 'Tentacle',
    tier: 2,
    effect:
      `${green('+3%')} Crit Chance<br/>${green('+20%')} chance to heal ${green('1')} HP when killing an enemy with a critical hit`,
    price: 35,
    limit: 5,
    tags: ['critChance'],
    position: [840, 180],
  },
  terrifiedOnion: {
    name: 'terrifiedOnion',
    nameText: 'Terrified Onion',
    tier: 1,
    effect: `${green('+4%')} Speed<br/>${red('-5')} Luck`,
    price: 15,
    limit: 0,
    tags: ['speed'],
    position: [840, 240],
  },
  toolbox: {
    name: 'toolbox',
    nameText: 'Toolbox',
    tier: 3,
    effect: `${green('+6')} Engineering<br/>${red('-8%')} Attack Speed`,
    price: 55,
    limit: 0,
    tags: ['engineering'],
    position: [840, 300],
  },
  torture: {
    name: 'torture',
    nameText: 'Torture',
    tier: 4,
    effect:
      `${green('+15')} Max HP<br/>Restore ${green('5')} HP per second. Cannot heal any other way.`,
    price: 100,
    limit: 1,
    tags: ['maxHP'],
    position: [840, 360],
  },
  toxicSludge: {
    name: 'toxicSludge',
    nameText: 'Toxic Sludge',
    tier: 1,
    effect: `${green('+2')} Elemental Damage<br/>${red('-2%')} Dodge`,
    price: 20,
    limit: 0,
    tags: ['elementalDamage'],
    position: [840, 420],
  },
  tractor: {
    name: 'tractor',
    nameText: 'Tractor',
    tier: 3,
    effect: `${green('+40')} Harvesting<br/>${red('-8%')} Damage`,
    price: 70,
    limit: 0,
    tags: ['harvesting'],
    position: [840, 480],
  },
  treasureMap: {
    name: 'treasureMap',
    nameText: 'Treasure Map',
    tier: 2,
    effect: `${green('+20%')} chance of finding an extra item in a crate`,
    price: 35,
    limit: 5,
    tags: ['luck'],
    position: [840, 540],
  },
  tree: {
    name: 'tree',
    nameText: 'Tree',
    tier: 1,
    effect: `More trees spawn`,
    price: 15,
    limit: 0,
    tags: ['exploration'],
    position: [840, 600],
  },
  triangleOfPower: {
    name: 'triangleOfPower',
    nameText: 'Triangle of Power',
    tier: 3,
    effect:
      `${green('+20%')} Damage<br/>${green('+1')} Armor<br/>${red('-2%')} Damage when you take damage until the end of the wave`,
    price: 65,
    limit: 0,
    tags: ['damage'],
    position: [840, 660],
  },
  turret: {
    name: 'turret',
    nameText: 'Turret',
    tier: 1,
    effect:
      `Spawns a turret that shoots bullets dealing ${green('10')} (<span>+80%${stat('engineering')}) damage</span>`,
    price: 15,
    limit: 0,
    tags: ['engineering', 'structure'],
    position: [840, 720],
  },
  tyler: {
    name: 'tyler',
    nameText: 'Tyler',
    tier: 3,
    effect:
      `Spawns a little guy that slowly shoots ${green('10')} piercing lightning projectiles around him for ${green('10')} (<span>+75%${stat('engineering')}+75%${stat('elementalDamage')}</span>) damage each`,
    price: 75,
    limit: 0,
    tags: ['engineering', 'elementalDamage', 'structure'],
    position: [840, 780],
  },
  uglyTooth: {
    name: 'uglyTooth',
    nameText: 'Ugly Tooth',
    tier: 1,
    effect:
      `Hitting an enemy removes ${green('5%')} of their speed. Max ${green('20%')}<br/>${red('-3%')} Speed`,
    price: 25,
    limit: 1,
    tags: ['lessEnemySpeed'],
    position: [0, 840],
  },
  vigilanteRing: {
    name: 'vigilanteRing',
    nameText: 'Vigilante Ring',
    tier: 3,
    effect: `${green('+3%')} Damage at the end of a wave`,
    price: 92,
    limit: 0,
    tags: ['damage'],
    position: [60, 840],
  },
  wanderingBot: {
    name: 'wanderingBot',
    nameText: 'Wandering Bot',
    tier: 3,
    effect: `Spawns a little bot that slows down nearby enemies`,
    price: 60,
    limit: 0,
    tags: ['lessEnemySpeed', 'structure'],
    position: [120, 840],
  },
  warriorHelmet: {
    name: 'warriorHelmet',
    nameText: 'Warrior Helmet',
    tier: 3,
    effect: `${green('+3')} Armor<br/>${green('+5')} Max HP<br/>${red('-5%')} Speed`,
    price: 80,
    limit: 0,
    tags: ['armor', 'maxHP'],
    position: [180, 840],
  },
  weirdFood: {
    name: 'weirdFood',
    nameText: 'Weird Food',
    tier: 1,
    effect: `${green('+2')} HP recovered from consumables<br/>${red('-2%')} Dodge`,
    price: 20,
    limit: 0,
    tags: ['consumable'],
    position: [240, 840],
  },
  weirdGhost: {
    name: 'weirdGhost',
    nameText: 'Weird Ghost',
    tier: 1,
    effect: `${green('+3')} Max HP<br/>Start the next wave with ${green('1')} HP`,
    price: 12,
    limit: 0,
    tags: ['maxHP'],
    position: [300, 840],
  },
  wheat: {
    name: 'wheat',
    nameText: 'Wheat',
    tier: 3,
    effect:
      `${green('+4')} Melee Damage<br/>${green('+2')} Ranged Damage<br/>${green('+10')} Harvesting<br/>${red('-2')} Elemental Damage`,
    price: 85,
    limit: 0,
    tags: ['meleeDamage', 'rangedDamage', 'harvesting'],
    position: [360, 840],
  },
  wheelbarrow: {
    name: 'wheelbarrow',
    nameText: 'Wheelbarrow',
    tier: 2,
    effect: `${green('+16')} Harvesting<br/>${red('-1')} Armor`,
    price: 40,
    limit: 0,
    tags: ['harvesting'],
    position: [420, 840],
  },
  whetstone: {
    name: 'whetstone',
    nameText: 'Whetstone',
    tier: 2,
    effect: `${green('+4%')} Life Steal<br/>${red('-3')} Knockback`,
    price: 40,
    limit: 0,
    tags: ['lifeSteal'],
    position: [480, 840],
  },
  whistle: {
    name: 'whistle',
    nameText: 'Whistle',
    tier: 1,
    effect:
      `${green('+50%')} chance for loot aliens to appear<br/>${green('+20%')} movement speed for loot aliens`,
    price: 25,
    limit: 1,
    tags: [],
    position: [540, 840],
  },
  whiteFlag: {
    name: 'whiteFlag',
    nameText: 'White Flag',
    tier: 2,
    effect: `${green('+5')} Harvesting<br/>-5% Enemies`,
    price: 40,
    limit: 1,
    tags: ['harvesting', 'lessEnemies'],
    position: [600, 840],
  },
  wings: {
    name: 'wings',
    nameText: 'Wings',
    tier: 3,
    effect:
      `${green('+10%')} Speed<br/>${green('+30')} Range<br/>${red('-2')} Elemental Damage`,
    price: 85,
    limit: 0,
    tags: ['speed', 'range'],
    position: [660, 840],
  },
  wisdom: {
    name: 'wisdom',
    nameText: 'Wisdom',
    tier: 3,
    effect:
      `${green('+5%')} Damage every 5 seconds until the end of the wave<br/>${red('-15%')} Damage`,
    price: 85,
    limit: 1,
    tags: ['damage'],
    position: [720, 840],
  },
  wolfHelmet: {
    name: 'wolfHelmet',
    nameText: 'Wolf Helmet',
    tier: 4,
    effect:
      `${green('+10')} Elemental Damage<br/>${green('+20')} Luck<br/>${red('-5')} Engineering`,
    price: 90,
    limit: 0,
    tags: ['elementalDamage', 'luck'],
    position: [780, 840],
  },
}

export default items
