const green = (v) => `<span class="green">${v}</span>`
const red = (v) => `<span class="red">${v}</span>`

const weaponClasses = {
  blade: {
    name: 'blade',
    nameText: 'Blade',
    bonuses: [
      [`${green('+1')} Melee Damage`, `${green('+1')} Life Steal`],
      [`${green('+2')} Melee Damage`, `${green('+2')} Life Steal`],
      [`${green('+3')} Melee Damage`, `${green('+3')} Life Steal`],
      [`${green('+4')} Melee Damage`, `${green('+4')} Life Steal`],
      [`${green('+5')} Melee Damage`, `${green('+5')} Life Steal`],
    ],
    weapons: [
      'chopper',
      'circularSaw',
      'sword',
      'captainsSword',
      'chainsaw',
      'thunderSword',
      'excalibur',
    ],
  },
  blunt: {
    name: 'blunt',
    nameText: 'Blunt',
    bonuses: [
      [`${green('+1')} Armor`, `${red('-2%')} Speed`],
      [`${green('+1')} Armor`, `${green('+3')} Max HP`, `${red('-4%')} Speed`],
      [`${green('+2')} Armor`, `${green('+3')} Max HP`, `${red('-6%')} Speed`],
      [`${green('+2')} Armor`, `${green('+6')} Max HP`, `${red('-8%')} Speed`],
      [`${green('+3')} Armor`, `${green('+6')} Max HP`, `${red('-10%')} Speed`],
    ],
    weapons: ['brick', 'rock', 'spoon', 'spikyShield', 'hammer', 'warHammer'],
  },
  elemental: {
    name: 'elemental',
    nameText: 'Elemental',
    bonuses: [
      [`${green('+1')} Elemental Damage`],
      [`${green('+2')} Elemental Damage`],
      [`${green('+3')} Elemental Damage`],
      [`${green('+4')} Elemental Damage`],
      [`${green('+5')} Elemental Damage`],
    ],
    weapons: [
      'icicle',
      'lightningShiv',
      'plank',
      'taser',
      'torch',
      'wand',
      'fireball',
      'flamethrower',
      'flamingBrassKnuckles',
      'particleAccelerator',
      'plasmaSledge',
      'thunderSword',
    ],
  },
  ethereal: {
    name: 'ethereal',
    nameText: 'Ethereal',
    bonuses: [
      [`${green('+6%')} Dodge`, `${red('-1')} Armor`],
      [`${green('+12%')} Dodge`, `${red('-2')} Armor`],
      [`${green('+18%')} Dodge`, `${red('-3')} Armor`],
      [`${green('+24%')} Dodge`, `${red('-4')} Armor`],
      [`${green('+30%')} Dodge`, `${red('-5')} Armor`],
    ],
    weapons: ['ghostAxe', 'ghostFlint', 'ghostScepter', 'scythe'],
  },
  explosive: {
    name: 'explosive',
    nameText: 'Explosive',
    bonuses: [
      [`${green('+5%')} Explosion Size`],
      [`${green('+10%')} Explosion Size`],
      [`${green('+15%')} Explosion Size`],
      [`${green('+20%')} Explosion Size`],
      [`${green('+25%')} Explosion Size`],
    ],
    weapons: [
      'plank',
      'shredder',
      'fireball',
      'grenadeLauncher',
      'rocketLauncher',
      'nuclearLauncher',
      'plasmaSledge',
      'powerFist',
      'dexTroyer',
    ],
  },
  gun: {
    name: 'gun',
    nameText: 'Gun',
    bonuses: [
      [`${green('+10')} Range`],
      [`${green('+20')} Range`],
      [`${green('+30')} Range`],
      [`${green('+40')} Range`],
      [`${green('+50')} Range`],
    ],
    weapons: [
      'doubleBarrelShotgun',
      'laserGun',
      'medicalGun',
      'pistol',
      'revolver',
      'shredder',
      'smg',
      'blunderbuss',
      'harpoonGun',
      'minigun',
      'sniperGun',
      'obliterator',
      'chainGun',
    ],
  },
  heavy: {
    name: 'heavy',
    nameText: 'Heavy',
    bonuses: [
      [`${green('+5%')} Damage`],
      [`${green('+10%')} Damage`],
      [`${green('+15%')} Damage`],
      [`${green('+20%')} Damage`],
      [`${green('+25%')} Damage`],
    ],
    weapons: [
      'cactiClub',
      'anchor',
      'flamethrower',
      'grenadeLauncher',
      'hammer',
      'mace',
      'rocketLauncher',
      'minigun',
      'nuclearLauncher',
      'obliterator',
      'warHammer',
      'particleAccelerator',
      'gatlingLaser',
    ],
  },
  legendary: {
    name: 'legendary',
    nameText: 'Legendary',
    bonuses: [
      [`${red('-20')} Max HP`],
      [`${red('-40')} Max HP`],
      [`${red('-60')} Max HP`],
      [`${red('-80')} Max HP`],
      [`${red('-100')} Max HP`],
    ],
    weapons: [
      'chainGun',
      'dexTroyer',
      'drill',
      'excalibur',
      'gatlingLaser',
      'scythe',
    ],
  },
  medical: {
    name: 'medical',
    nameText: 'Medical',
    bonuses: [
      [`${green('+1')} HP Regeneration`],
      [`${green('+2')} HP Regeneration`],
      [`${green('+3')} HP Regeneration`],
      [`${green('+4')} HP Regeneration`],
      [`${green('+5')} HP Regeneration`],
    ],
    weapons: ['medicalGun', 'scissors', 'circularSaw'],
  },
  medieval: {
    name: 'medieval',
    nameText: 'Medieval',
    bonuses: [
      [`${green('+1')} Armor`],
      [`${green('+1')} Armor`, `${green('+3%')} Dodge`],
      [`${green('+2')} Armor`, `${green('+3%')} Dodge`],
      [`${green('+2')} Armor`, `${green('+6%')} Dodge`],
      [`${green('+3')} Armor`, `${green('+6%')} Dodge`],
    ],
    weapons: [
      'crossbow',
      'joustingLance',
      'quarterstaff',
      'spikyShield',
      'mace',
      'sword',
      'trident',
    ],
  },
  musical: {
    name: 'musical',
    nameText: 'Musical',
    bonuses: [
      [`${green('+5')} Luck`],
      [`${green('+10')} Luck`],
      [`${green('+15')} Luck`],
      [`${green('+20')} Luck`],
      [`${green('+25')} Luck`],
    ],
    weapons: ['flute', 'lute'],
  },
  naval: {
    name: 'naval',
    nameText: 'Naval',
    bonuses: [
      [`${green('+1')} Curse`],
      [`${green('+2')} Curse`],
      [`${green('+3')} Curse`],
      [`${green('+4')} Curse`],
      [`${green('+5')} Curse`],
    ],
    weapons: [
      'anchor',
      'blunderbuss',
      'harpoonGun',
      'trident',
      'captainsSword',
    ],
  },
  precise: {
    name: 'precise',
    nameText: 'Precise',
    bonuses: [
      [`${green('+3%')} Crit Chance`],
      [`${green('+6%')} Crit Chance`],
      [`${green('+9%')} Crit Chance`],
      [`${green('+12%')} Crit Chance`],
      [`${green('+15%')} Crit Chance`],
    ],
    weapons: [
      'claw',
      'crossbow',
      'icicle',
      'knife',
      'lightningShiv',
      'scissors',
      'sharpTooth',
      'shuriken',
      'thiefDagger',
      'sniperGun',
      'drill',
    ],
  },
  primitive: {
    name: 'primitive',
    nameText: 'Primitive',
    bonuses: [
      [`${green('+3')} Max HP`],
      [`${green('+6')} Max HP`],
      [`${green('+9')} Max HP`],
      [`${green('+12')} Max HP`],
      [`${green('+15')} Max HP`],
    ],
    weapons: [
      'cactiClub',
      'hatchet',
      'javelin',
      'quarterstaff',
      'rock',
      'sharpTooth',
      'slingshot',
      'spear',
      'stick',
      'torch',
    ],
  },
  support: {
    name: 'support',
    nameText: 'Support',
    bonuses: [
      [`${green('+5')} Harvesting`],
      [`${green('+10')} Harvesting`],
      [`${green('+15')} Harvesting`],
      [`${green('+20')} Harvesting`],
      [`${green('+25')} Harvesting`],
    ],
    weapons: [
      'hand',
      'hikingPole',
      'lute',
      'pruner',
      'sickle',
      'taser',
      'potatoThrower',
    ],
  },
  tool: {
    name: 'tool',
    nameText: 'Tool',
    bonuses: [
      [`${green('+1')} Engineering`],
      [`${green('+2')} Engineering`],
      [`${green('+3')} Engineering`],
      [`${green('+4')} Engineering`],
      [`${green('+5')} Engineering`],
    ],
    weapons: ['screwdriver', 'wrench', 'chainsaw'],
  },
  unarmed: {
    name: 'unarmed',
    nameText: 'Unarmed',
    bonuses: [
      [`${green('+3%')} Dodge`],
      [`${green('+6%')} Dodge`],
      [`${green('+9%')} Dodge`],
      [`${green('+12%')} Dodge`],
      [`${green('+15%')} Dodge`],
    ],
    weapons: ['claw', 'fist', 'hand', 'flamingBrassKnuckles', 'powerFist'],
  },
}

export default weaponClasses
